import {TARGETS} from './catalog.js';
import {PROFILES,POLICY_VERSION} from './policy.js';
import {createSession,applySession} from './session.js';
import {JsonStore} from './storage.js';

const root=document.getElementById('app'),status=document.getElementById('status');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const phaseLabel={initial:'초기 확인',movement:'이동',combat:'전투',recovery:'회복',supply:'보급',soviet_turn:'소련군 차례',victory:'승리 판정'};
let store,record=null,candidates=[];
const notice=(message,error=false)=>{status.textContent=message;status.className=error?'error':'';};
const optionTargets=TARGETS.map(t=>`<option value="${esc(t.id)}">${esc(t.name)} · ${t.vp}VP</option>`).join('');
const vpCheckboxes=TARGETS.filter(t=>t.type==='vp_hex').map(t=>`<label><input type="checkbox" name="controlled" value="${esc(t.id)}">${esc(t.name)} (${t.vp})</label>`).join('');
const isolatedCheckboxes=TARGETS.filter(t=>t.type==='vp_hex').map(t=>`<label><input type="checkbox" name="isolated" value="${esc(t.id)}">${esc(t.name)}</label>`).join('');

async function commit(next) {
  const saved=await store.write(next,next.history,record.id,record.revision);
  record=saved;
  notice('저장했습니다.');
  render();
}
async function transition(...actions) {
  let next=record.state;
  for(const action of actions) next=applySession(next,action);
  await commit(next);
}
function landing(records) {
  root.innerHTML=`<div class="grid"><section class="panel"><p class="eyebrow">새 게임</p><h2>S1 Fall Blau 시작</h2><label>난이도 <select id="difficulty">${Object.entries(PROFILES).map(([id,p])=>`<option value="${id}" ${id==='standard'?'selected':''}>${p.label} · 소련군 목표 승률 ${Math.round(p.targetHumanWinRate*100)}% (미측정)</option>`).join('')}</select></label><div class="actions"><button data-action="new">새 기록 만들기</button><a class="button" href="./paper.html">종이판 열기</a></div><p class="muted">현재 정책 ${POLICY_VERSION}. 승률은 향후 종이 테스트로 조정합니다.</p></section><aside class="panel"><h2>저장한 게임</h2>${records.length?`<ul class="list">${records.map(r=>`<li><button class="secondary" data-action="load" data-id="${esc(r.id)}">${esc(r.state.turn)}턴 · ${esc(PROFILES[r.state.difficulty]?.label)} · ${esc(r.state.phase)}</button></li>`).join('')}</ul>`:'<p class="muted">저장 기록이 없습니다.</p>'}<label>JSON 가져오기 <input type="file" id="import" accept="application/json,.json"></label></aside></div>`;
}
function candidateForm(s) {
  return `<section class="panel"><p class="eyebrow">후보 만들기</p><h2>실물 보드에서 확인한 선택지</h2><form id="candidate-form"><div class="row"><label>담당 편제 <input name="formation" required placeholder="예: 6A"></label><label>사용 유닛 ID (쉼표 구분) <input name="units" required placeholder="예: 6A-1, 6A-2"></label></div><div class="row"><label>목표 <select name="target">${optionTargets}</select></label><label>행동 <select name="action"><option value="advance">접근·이동</option><option value="attack">공격 준비</option><option value="restore_supply">보급 회복</option><option value="defend">방어</option></select></label></div><div class="row"><label>이동 헥스 수 <input type="number" name="hexes" min="0" value="1"></label><label>남길 예비 병력 수 <input type="number" name="reserve" min="0" value="2"></label></div><div class="row"><label>포위 위험 <select name="risk"><option value="none">없음</option><option value="low">낮음</option><option value="high">높음</option></select></label><label>예상 공격 비율 (공격 시) <input type="number" name="odds" min="0" step="0.1" value="1.5"></label></div><label>예상 손실 위험 0–1 (공격 시) <input type="number" name="loss" min="0" max="1" step="0.05" value="0.25"></label><div class="checks"><label><input type="checkbox" name="legal" checked>이동·공격 합법 확인</label><label><input type="checkbox" name="supplied" checked>보급 유지 확인</label><label><input type="checkbox" name="reachable" checked>목표 접근 가능</label></div><button type="submit">후보 추가</button></form><p class="tiny">첫 턴의 14Pz·22Pz·60PzG와 전술 이동 2헥스 제한을 적용합니다. 전투 적격성과 실제 전투 결과는 따로 확인합니다.</p></section>`;
}
function vpForm(){return `<section class="panel"><p class="eyebrow">S1.3</p><h2>소련군 차례 완료 및 VP 관측</h2><form id="vp-form"><p>추축군 점령 VP 헥스</p><div class="checks">${vpCheckboxes}</div><p>소련 보급원에서 고립된 미점령 VP 헥스</p><div class="checks">${isolatedCheckboxes}</div><div class="row"><fieldset><legend>동쪽 출구</legend><label>기계화 스텝 <input type="number" name="eastSteps" min="0" value="0"></label><label><input type="checkbox" name="eastRoad">도로 보급</label></fieldset><fieldset><legend>남쪽 출구</legend><label>기계화 스텝 <input type="number" name="southSteps" min="0" value="0"></label><label><input type="checkbox" name="southRoad">도로 보급</label></fieldset></div><label><input type="checkbox" name="don">Don강 남쪽 독일 전투 유닛</label><button type="submit">소련군 차례 완료 · VP 판정</button></form></section>`;}
function game(s) {
  const choice=s.decision?.selected;
  const candidateItems=candidates.map(c=>`<li>${esc(c.formationId)} / ${esc(TARGETS.find(t=>t.id===c.targetId)?.name)} / ${esc(c.action)} / ${esc(c.units.join(', '))}</li>`).join('');
  root.innerHTML=`<div class="summary"><span class="pill">${s.turn} / 8턴</span><span class="pill">${esc(phaseLabel[s.phase])}</span><span class="pill">${s.vp} / 8 VP</span><span class="pill">${esc(PROFILES[s.difficulty].label)}</span></div><div class="grid"><div><section class="panel"><p class="eyebrow">현재 단계</p><h2>${esc(phaseLabel[s.phase])}</h2><p>${esc(s.message)}</p>${s.winner?`<div class="card"><b>${s.winner==='axis'?'추축군':'소련군'} 승리</b> · S1.3</div>`:''}${s.phase==='soviet_turn'&&!s.winner?vpForm():''}${['movement','combat','recovery','supply'].includes(s.phase)&&!s.winner?candidateForm(s):''}${candidateItems?`<h3>이번 검토 후보</h3><ol class="list">${candidateItems}</ol><label>공개 d6 <input id="die" type="number" min="1" max="6" value="1"></label><button data-action="decide">후보 평가</button>`:''}${s.decision?`<div class="card"><h3>평가 결과</h3>${s.decision.questions.length?`<p>${esc(s.decision.questions.join(' · '))}</p>`:`<p>${choice?`${esc(choice.action)} / ${esc(choice.targetId??'대체 행동')}`:'선택 보류'}</p>`}<p class="tiny">정책 ${esc(s.decision.policyIds.join(', '))} · 영문 ${esc(s.decision.ruleRefs.join(', '))}</p>${s.decision.rejected.length?`<p>제외: ${esc(s.decision.rejected.map(r=>`${r.id} (${r.policyId})`).join(', '))}</p>`:''}${choice&&!s.decision.questions.length?`<div class="actions"><button data-action="confirm">실행 확인 후 확정</button><button class="secondary" data-action="reject">실행 불가 · 다음 후보</button></div>`:''}</div>`:''}<div class="actions">${s.phase!=='victory'&&s.phase!=='soviet_turn'&&!s.winner?`<button class="secondary" data-action="next_phase">다음 단계</button>`:''}${s.phase==='victory'&&!s.winner?`<button data-action="next_turn">다음 턴</button>`:''}<button class="secondary" data-action="undo" ${s.undoStack.length?'':'disabled'}>마지막 확정 취소</button></div></section></div><aside><section class="panel"><h2>게임 기록</h2><p class="tiny">정책 ${esc(s.policyVersion)} · 영문 규칙 v2.1</p><ol class="list">${s.history.slice(-8).map(h=>`<li>${h.turn}턴 ${esc(h.phase??'판정')} · ${esc(h.type)} · ${esc(h.policyIds?.join(', ')??h.vp+'VP')}</li>`).join('')}</ol><div class="actions"><button class="secondary" data-action="export">JSON 내보내기</button><button class="secondary" data-action="home">목록</button></div></section></aside></div>`;
}
async function render(){if(record)game(record.state);else landing(await store.listing());}
function formCandidate(form){const f=new FormData(form),action=f.get('action');return {id:crypto.randomUUID(),targetId:f.get('target'),formationId:f.get('formation').trim(),action,units:f.get('units').split(',').map(x=>x.trim()).filter(Boolean),hexes:Number(f.get('hexes')),reserveRemaining:Number(f.get('reserve')),encirclementRisk:f.get('risk'),legal:f.has('legal'),supplied:f.has('supplied'),reachable:f.has('reachable'),...(action==='attack'?{attack:{odds:Number(f.get('odds')),lossRisk:Number(f.get('loss'))}}:{})};}
function formVp(form){const f=new FormData(form);return {sovietTurnComplete:true,vp:{controlledVpHexes:f.getAll('controlled').map(id=>({id,supplied:true})),isolatedSovietVpHexes:f.getAll('isolated'),eastExit:{mechanizedSteps:Number(f.get('eastSteps')),roadSupply:f.has('eastRoad')},southExit:{mechanizedSteps:Number(f.get('southSteps')),roadSupply:f.has('southRoad')},donSouthGermanCombatUnit:f.has('don')}};}
root.addEventListener('submit',async event=>{event.preventDefault();try{if(event.target.id==='candidate-form'){candidates.push(formCandidate(event.target));render();notice('후보를 추가했습니다.');}else if(event.target.id==='vp-form'){await transition({type:'observe',observation:formVp(event.target)},{type:'next_phase'});candidates=[];}}catch(e){notice(e.message,true);}});
root.addEventListener('click',async event=>{const button=event.target.closest('button[data-action]');if(!button)return;try{switch(button.dataset.action){case 'new':record=await store.write(createSession({difficulty:document.getElementById('difficulty').value}),[],undefined,0);candidates=[];render();notice('새 게임을 저장했습니다.');break;case 'load':record=await store.read(button.dataset.id);candidates=[];render();notice('기록을 열었습니다.');break;case 'home':record=null;candidates=[];render();break;case 'next_phase':await transition({type:'next_phase'});candidates=[];break;case 'next_turn':await transition({type:'next_turn'});candidates=[];break;case 'decide':await transition({type:'decide',candidates,die:Number(document.getElementById('die').value)});break;case 'confirm':{const s=record.state,choice=s.decision.selected;const combatResolved=s.phase==='combat'?window.confirm('실물 보드에서 전투를 해결하고 결과를 확인했습니까?'):false;if(s.phase==='combat'&&!combatResolved)break;await transition({type:'confirm',candidate:{...choice,units:choice.units??[]},policyIds:s.decision.policyIds,ruleRefs:s.decision.ruleRefs,die:Number(document.getElementById('die')?.value??1),combatResolved});candidates=[];break;}case 'reject':{const rejectedId=record.state.decision.selected.id;await transition({type:'reject',reason:'실물 보드에서 실행 불가'});candidates=candidates.filter(c=>c.id!==rejectedId);break;}case 'undo':await transition({type:'undo'});break;case 'export':{const json=await store.exportJson(record.id),url=URL.createObjectURL(new Blob([json],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`stalingrad42-${record.id}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notice('JSON을 내보냈습니다.');break;}}}catch(e){notice(e.message,true);}});
root.addEventListener('change',async event=>{if(event.target.id!=='import')return;try{const file=event.target.files[0];if(!file)return;record=await store.importJson(await file.text());candidates=[];render();notice('새 저장 ID로 가져왔습니다.');}catch(e){notice(e.message,true);}});
try{store=await JsonStore.open();await render();}catch(e){notice(e.message,true);root.innerHTML='<section class="panel"><h2>웹 저장을 사용할 수 없습니다</h2><p>종이 순서도로 계속 플레이할 수 있습니다.</p><a href="./paper.html">종이판 열기</a></section>';}
