import {JsonStore} from './storage.js';
import {diceForCard,faceIndices} from './dice-data.js?v=20260923-2';
const $ = s => document.querySelector(s);
const STORE = 'ccbot-ko-session:' + location.pathname;
const NATIONS = {American:'미국',German:'독일',Russian:'소련',British:'영국',French:'프랑스',Italian:'이탈리아'};
const SHEETS = Object.fromEntries(Object.keys(NATIONS).map(n=>[n,{first:n==='French'?'French_Deck1.png':`${n}_deck1.png`,second:n==='French'?'French_Deck2.png':`${n}_deck2.png`,extra:n==='American'?5:3,cols:n==='American'?3:2}]));
const POSTURES = {Recon:{label:'정찰',counts:[1,2,1,1,1],order:0,action:5},Attack:{label:'공격자',counts:[1,1,1,2,1],order:0,action:8},Defense:{label:'방어자',counts:[1,1,1,1,2],order:1,action:5}};
const ORDER_CHECK=[2,2,3,3,4,5,6], ACTION_CHECK=[6,5,5,4,4,3,3,3,2,2];
const ORDER_TRACKS=[
 {name:'포병',items:['포병 요청','포병 요청','포병 거부','포병 요청','포병 요청','포병 거부','포병 요청']},
 {name:'기본 훈련',items:['이동','이동','사격','이동','사격','패주','이동','회복','사격','이동','전진','사격'],special:[3,9]},
 {name:'지원',items:['회복','회복','패주','회복']},
 {name:'강습',items:['사격','이동','사격','전진','사격','전진','이동','전진','사격','사격','전진','패주'],special:[1,2,6,9]},
 {name:'유지·방어',items:['사격','사격','사격','사격','패주','사격','회복','사격','사격','패주','사격','회복'],special:[1,3,8]}
];
const TRIGGERS=[
 {id:'oppFire',name:'상대가 사격 명령을 사용',actions:[['6','Hidden Pillbox','시나리오 방어자 · 목표가 목표 지점','4+'],['4–5','Hidden Entrenchments','시나리오 방어자','3+'],['1–3','Concealment','없음','3+']]},
 {id:'oppMove1',name:'(1) 상대가 이동 또는 전진 명령을 사용',actions:[['5–6','Hidden Mines','시나리오 방어자','5+'],['1–4','Hidden Wire','시나리오 방어자','5+']]},
 {id:'oppMove2',name:'(2) 상대가 이동 명령을 사용',actions:[['–','Op-Fire','이동 유닛이 아군 유닛의 LOS와 사거리 내','태세·국가별']]},
 {id:'oppPass',name:'상대가 패스로 인해 카드를 버림',actions:[['5–6','Demolitions','없음','5+'],['1–4','Hidden Unit','시나리오 방어자','4+']]},
 {id:'melee',name:'근접전 발생',actions:[['–','Ambush','없음','5+']]},
 {id:'winMelee',name:'봇이 근접전 승리',actions:[['–','No Quarter','봇 독일·상대 소련 또는 봇 소련','6+']]},
 {id:'break',name:'아군 분대가 사기 저하될 상황',actions:[['–','Light Wounds','없음','5+']]},
 {id:'time',name:'TIME! 이벤트',actions:[['–','Dig-In','완료 후 행동 덱 섞기','5+']]},
 {id:'botMove',name:'봇이 특별 이동 명령 사용',actions:[['5–6','Assault Fire','박스 표시 사격력','4+'],['1–4','Smoke Grenades','없음','미국 4+ / 그 외 5+']]},
 {id:'botFire',name:'봇이 특별 사격 명령 사용 / 기회 사격 중 특별 사격 칸에 토큰',actions:[['선택','Bore Sighting','시나리오 방어자','프랑스 5+ / 그 외 6+'],['선택','Crossfire','Op-Fire','4+'],['선택','Hand Grenades','목표가 인접','4+'],['선택','Spray Fire','박스 표시 사거리','4+'],['선택','Sustained Fire','MG 또는 박격포가 사격','5+'],['선택','Marksmanship','봇 독일 또는 영국','영국 4+ / 독일 5+']]}
];
let state, history=[], store, saveId=null, revision=-1, busy=false;
function shuffle(a){const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b}
function fullDeck(n){return shuffle(faceIndices(n))}
function fresh(){return {version:1,stage:'config',nation:'German',actionNation:'German',posture:'Defense',firstPlayer:'bot',orderLimit:4,handLimit:4,actionTableMode:'all',tokenPositions:[],setupQueue:[],setupIndex:0,setupCard:null,orderIndex:1,actionIndex:5,botDeck:[],botDiscard:[],hand:[],actionDeck:[],actionDiscard:[],currentCard:null,currentDice:null,activeOrder:null,action:null,returnStage:null,time:null,turn:1,log:[]}}
async function persist(){const data=await store.write(state,history,saveId,revision);saveId=data.id;revision=data.revision;try{localStorage.setItem(STORE,saveId)}catch{}$('#saveStatus').textContent=`JSON 저장됨 · r${revision}`}
async function commit(fn,msg){if(busy||!store)return;busy=true;const before=structuredClone(state),oldHistory=structuredClone(history),oldId=saveId,oldRevision=revision;try{history.push(before);if(history.length>80)history.shift();fn();if(msg)state.log.unshift(msg);await persist();render()}catch(error){state=before;history=oldHistory;saveId=oldId;revision=oldRevision;render();notice('저장 실패: '+error.message);$('#saveStatus').textContent='저장되지 않음'}finally{busy=false}}
function notice(msg){$('#notice').textContent=msg||''}
function cardMarkup(n,id,caption='운명 카드'){
 if(id===null||id===undefined)return '';
 let sheet,col,row,cols,rows;
 if(id<70){sheet=SHEETS[n].first;cols=10;rows=7;col=id%10;row=Math.floor(id/10)}else{sheet=SHEETS[n].second;cols=SHEETS[n].cols;rows=2;let i=id-70;col=i%cols;row=Math.floor(i/cols)}
 return `<div class="card-figure"><div class="fate-card" role="img" aria-label="${caption}" style="background-image:url('cardimage/${sheet}');background-size:${cols*100}% ${rows*100}%;background-position:${col/(cols-1)*100}% ${row/(rows-1)*100}%"></div><div class="card-caption">${caption}</div></div>`
}
function backMarkup(n){let p=SHEETS[n],i=p.extra;return cardMarkup(n,70+i,'뒷면 카드')}
function diceDisplay(n,id,includeRed=true){const dice=diceForCard(n,id);return `<div class="dice-row" aria-label="카드에 인쇄된 주사위 값"><span class="die-tag white">흰색 ${dice.white}</span>${includeRed?`<span class="die-tag red">빨간색 ${dice.red}</span>`:''}</div>${includeRed?'<p class="hint">규칙서의 “검은색 주사위”는 이 카드 그림의 빨간색 주사위입니다.</p>':''}`}
function correctOldSave(s){let changed=false;const clean=(name)=>{const before=s[name].length;s[name]=s[name].filter(id=>id!==69);changed ||= s[name].length!==before};if(s.nation==='American'){for(const name of ['botDeck','botDiscard','hand'])clean(name);if(s.setupCard===69){s.setupCard=null;changed=true}if(s.currentCard===69){s.currentCard=null;if(s.stage==='orderCheck')s.stage='botReady';changed=true}}if(s.actionNation==='American'){for(const name of ['actionDeck','actionDiscard'])clean(name);if(s.action?.card===69){s.action.card=null;s.action.targetCard=null;s.action.white=null;s.action.red=null;s.action.selected=null;s.action.extra=0;s.action.phase='draw';changed=true}else if(s.action?.targetCard===69){s.action.targetCard=null;s.action.phase='requirements';changed=true}}if(changed)s.log.unshift('이전 버전이 카드로 취급한 미국 시트의 뒷면 칸을 제외했습니다. 진행 중이던 판정은 다시 시작하세요.');return changed}
function recoverOldTime(s){if(s.time||s.botDeck.length||!s.botDiscard.length||!['player','botReady'].includes(s.stage))return false;const resume=s.stage;s.time={step:0,resume,botDigInDone:false};s.stage='time';s.log.unshift('이전 저장 파일에서 봇 운명 덱의 마지막 카드 시간 절차를 시작합니다.');return true}
function drawBot(){if(!state.botDeck.length){notice('봇 운명 카드 덱이 비었습니다. 마지막 카드의 시간 절차를 먼저 처리하세요.');return null}return state.botDeck.pop()}
function drawAction(){if(!state.actionDeck.length){state.actionDeck=shuffle(state.actionDiscard);state.actionDiscard=[];state.log.unshift('행동 덱의 버린 카드를 섞어 새 행동 덱을 만들었습니다.')}return state.actionDeck.pop()??null}
function initGame(){const p=POSTURES[state.posture],q=[];p.counts.forEach((count,t)=>{for(let k=0;k<count;k++)q.push({token:q.length+1,track:t})});state.tokenPositions=q.map(x=>({...x,pos:0}));state.setupQueue=q;state.setupIndex=0;state.setupCard=null;state.orderIndex=state.nation==='French'?2:p.order;state.actionIndex=p.action;state.botDeck=fullDeck(state.nation);state.actionDeck=fullDeck(state.actionNation);state.botDiscard=[];state.actionDiscard=[];state.hand=[];state.stage='setup';state.log=[]}
function finishSetup(){state.botDeck=fullDeck(state.nation);state.botDiscard=[];const count=Math.min(state.orderLimit,state.handLimit);for(let i=0;i<count;i++){let c=drawBot();if(c!==null)state.hand.push(c)}state.turn=state.firstPlayer==='player'?0:1;state.stage=state.firstPlayer==='player'?'player':'botReady';state.log.unshift(`준비 완료 · 손패 ${state.hand.length}장 · ${state.firstPlayer==='player'?'플레이어':'봇'} 선공`)}
function startAction(triggerId,from){state.returnStage=from;state.action={triggerId,phase:'draw',card:null,white:null,red:null,selected:null,extra:0,passed:false};state.stage='action'}
function actionTarget(a){if(a[1]==='Op-Fire'){if(state.posture==='Recon')return state.nation==='American'?5:6;if(state.posture==='Attack')return 6;return state.nation==='American'?4:5}if(a[1]==='Smoke Grenades')return state.nation==='American'?4:5;if(a[1]==='Bore Sighting')return state.nation==='French'?5:6;if(a[1]==='Marksmanship')return state.nation==='British'?4:5;return Number(a[3].match(/\d/)[0])}
function pickAction(t,red){if(t.id==='botFire')return null;if(t.actions.length===1)return 0;return t.actions.findIndex(a=>a[0].split('–').map(Number).length===2?red>=Number(a[0].split('–')[0])&&red<=Number(a[0].split('–')[1]):red===Number(a[0]))}
function nextBotOrder(red){const token=state.tokenPositions.find(x=>x.token===red);if(!token)return null;const track=ORDER_TRACKS[token.track],pos=(token.pos+1)%track.items.length;return {token:red,track:token.track,pos,name:track.items[pos],special:!!track.special?.includes(pos)}}
function finishAction(){let a=state.action;if(a.extra>0){a.extra--;a.phase='draw';a.card=null;a.white=null;a.red=null;a.selected=null;a.passed=false;state.log.unshift('흰색 6: 같은 트리거의 추가 행동 판정');return}state.stage=state.returnStage;state.action=null;state.returnStage=null}
function startTime(resume='endTurn'){state.time={step:0,resume,botDigInDone:false,currentSpace:null,suddenSpace:null,suddenRoll:null};state.stage='time';state.log.unshift('봇 운명 덱의 마지막 카드: 시간 마커를 1칸 전진하고 시간 절차 시작')}
function refillBotHand(){const target=Math.min(state.orderLimit,state.handLimit);while(state.hand.length<target){if(!state.botDeck.length){startTime();return}const card=drawBot();if(card===null)return;state.hand.push(card);if(!state.botDeck.length){startTime();return}}state.stage='player'}
function timeView(){const step=state.time.step;const items=[
 ['시간 마커 +1','뽑기 더미의 마지막 카드를 뽑았습니다. 시간! 트리거와 같이 시간 마커를 정확히 1칸 전진시킨 뒤 일반 진행을 멈춥니다. 마지막 카드의 주사위 굴림에서도 시간!이 나왔다면 두 칸이 아닌 한 칸만 전진합니다.'],
 ['1 · 뽑기 더미 재구성','시간 전진을 유발한 봇만 자신의 운명 덱과 버린 카드 더미를 섞어 새 뽑기 더미를 만듭니다. 손패 카드는 그대로 둡니다.'],
 ['2 · 돌연 종료 확인','현재 시간 마커가 돌연 종료 마커가 있는 칸에 도달했거나 그 이후라면, 방금 섞은 봇 운명 덱에서 한 장을 뽑아 돌연 종료 굴림을 합니다. 두 주사위의 합이 현재 시간 마커 칸의 숫자보다 작으면 즉시 게임이 끝납니다. 굴림 중 카드의 다른 트리거는 무시합니다.'],
 ['3 · 방어자 +1 VP','돌연 종료로 게임이 끝나지 않았다면 방어자만 1 VP를 얻습니다. 실제 VP 마커를 갱신하세요.'],
 ['4 · 연막 제거','시간 전진을 유발한 봇만 지도에서 연막 마커 하나를 제거합니다.'],
 ['5 · 유닛 재배치','시간 마커가 도착한 칸의 유닛이 있다면 소유 플레이어의 지도 가장자리 헥스에 증원으로 배치합니다. 비활성 플레이어가 먼저 배치하고 스태킹 한도 [8]을 지킵니다. 증원 무전기는 자신의 빈 포병 칸에 놓습니다.'],
 ['6 · 진지 구축','양쪽은 진지 구축 행동을 사용할 수 있습니다. 봇의 TIME! 트리거는 제공된 CC: BOT 행동 표에 따라 행동 판정을 합니다.']
 ];const [title,description]=items[step],roll=state.time.suddenRoll;const holder=state.time.initiativeHolder??'';const sudden=step===2?`<div class="form-grid"><div class="field"><label for="currentSpace">전진 후 현재 시간 마커 칸 숫자</label><input id="currentSpace" type="number" min="0" step="1" value="${state.time.currentSpace??''}" ${roll?'disabled':''}></div><div class="field"><label for="suddenSpace">시나리오의 돌연 종료 마커 칸 숫자</label><input id="suddenSpace" type="number" min="0" step="1" value="${state.time.suddenSpace??''}" ${roll?'disabled':''}></div></div>${roll?`<div class="row">${cardMarkup(state.nation,roll.card,'돌연 종료 굴림 카드')}<div class="decision"><h3>자동 굴림 결과 · 주도권 확인 전</h3>${diceDisplay(state.nation,roll.card)}<div class="result">${roll.white} + ${roll.red} = <strong>${roll.total}</strong> · 현재 시간 칸 <strong>${state.time.currentSpace}</strong>${roll.total<state.time.currentSpace?'보다 작아 돌연 종료 조건을 충족합니다.':'보다 작지 않아 계속 진행할 수 있습니다.'} <strong>주도권 사용 여부를 결정한 뒤 결과를 적용하세요.</strong></div></div></div><div class="callout">주도권 카드 §10: 봇은 가능하면 카드를 보유하고, 돌연 종료에서는 자신에게 유리하게 사용하려 합니다. 정해진 자동 판단 기준은 없으므로 플레이어가 결정합니다. 재굴림을 선택하면 마지막 굴림의 효과를 취소하고 카드를 상대에게 넘깁니다.</div><div class="field"><label for="initiativeHolder">현재 주도권 카드 보유자</label><select id="initiativeHolder"><option value="" ${!holder?'selected':''}>실제 카드 확인</option><option value="bot" ${holder==='bot'?'selected':''}>봇</option><option value="player" ${holder==='player'?'selected':''}>플레이어</option></select></div><div class="actions"><button class="secondary" data-action="timeInitiativeReroll">주도권 사용 · 다시 굴림</button><button class="primary" data-action="timeApplyRoll">${roll.total<state.time.currentSpace?'결과 확정 · 게임 종료 →':'결과 확정 · 다음 단계 →'}</button></div><p class="hint">다시 굴린 결과에도 주도권을 사용할 수 있습니다. 실제 카드 보유자를 확인하세요.</p>`:'<div class="actions"><button class="primary" data-action="timeCheck">돌연 종료 해당 여부 및 굴림 확인 →</button></div>'}`:'';return `<div class="panel-head"><div><div class="kicker">시간 절차 · ${step+1} / 7</div><h2>${title}</h2><p class="lead">일반 진행을 잠시 멈췄습니다. 아래 순서대로 실제 게임판을 처리하세요.</p></div><span class="step-count">마지막 카드</span></div><div class="callout warning">${description}</div>${step===2?sudden:step===6?`<div class="actions">${!state.time.botDigInDone?'<button class="primary" data-action="timeDigIn">봇의 TIME! 행동 판정 →</button>':'<span class="tag">봇 행동 판정 완료</span>'}<button class="secondary" data-action="timeNext" ${!state.time.botDigInDone?'disabled':''}>양쪽 진지 구축 처리 완료 · 진행 재개 →</button></div>`:`<div class="actions"><button class="primary" data-action="timeNext">${step===0?'시간 마커 전진 완료 →':step===1?'덱 재구성 완료 →':'처리 완료 →'}</button></div>`}<p class="hint">행동 덱의 소진 절차는 CC: BOT 규칙에 따라 별도로 처리합니다.</p>`}
function gameOverView(){const roll=state.time?.suddenRoll;return `<div class="panel-head"><div><div class="kicker">게임 종료</div><h2>돌연 종료</h2><p class="lead">두 주사위 합이 현재 시간 마커 칸 숫자보다 작아 게임이 즉시 끝났습니다. 이후 시간 절차는 진행하지 않습니다.</p></div></div>${roll?`<div class="row">${cardMarkup(state.nation,roll.card,'돌연 종료 굴림 카드')}<div class="decision">${diceDisplay(state.nation,roll.card)}<div class="result">${roll.white} + ${roll.red} = <strong>${roll.total}</strong> &lt; 현재 시간 칸 <strong>${state.time.currentSpace}</strong></div></div></div>`:''}<div class="callout">비밀 목표를 공개하여 VP를 부여한 뒤 승자를 결정하세요 [6.3.2]. 동점이면 현재 주도권 카드 보유자가 승리합니다 [9.2]. 기록은 브라우저 JSON 파일에 보관됩니다.</div>`}
function e(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function configView(){return `<div class="panel-head"><div><div class="kicker">01 · 게임 준비</div><h2>봇을 설정하세요</h2><p class="lead">시나리오를 준비한 뒤 모든 목표를 공개 목표로 취급합니다.</p></div><span class="step-count">규칙 §3</span></div><div class="form-grid"><div class="field"><label for="nation">봇 국가</label><select id="nation">${Object.entries(NATIONS).map(([k,v])=>`<option value="${k}" ${state.nation===k?'selected':''}>${v}</option>`).join('')}</select></div><div class="field"><label for="posture">봇 태세</label><select id="posture">${Object.entries(POSTURES).map(([k,v])=>`<option value="${k}" ${state.posture===k?'selected':''}>${v.label}</option>`).join('')}</select></div><div class="field"><label for="actionNation">행동 덱 카드 이미지</label><select id="actionNation">${Object.entries(NATIONS).map(([k,v])=>`<option value="${k}" ${state.actionNation===k?'selected':''}>${v}</option>`).join('')}</select></div><div class="field"><label for="firstPlayer">첫 턴 진행</label><select id="firstPlayer"><option value="bot" ${state.firstPlayer!=='player'?'selected':''}>봇 선공</option><option value="player" ${state.firstPlayer==='player'?'selected':''}>플레이어 선공</option></select></div><div class="field"><label for="orderLimit">시나리오 명령 한도</label><input id="orderLimit" type="number" min="1" max="30" value="${state.orderLimit}"></div><div class="field"><label for="handLimit">봇 최대 손패 한도</label><input id="handLimit" type="number" min="1" max="30" value="${state.handLimit}"></div></div><div class="callout"><strong>시작 손패:</strong> 두 한도 중 작은 값. 준비 표에 따라 번호 토큰 6개를 위에서 아래로 배치하고, 토큰마다 카드의 흰색 주사위만큼 오른쪽으로 이동시킵니다.</div><div class="actions"><button class="primary" data-action="startSetup">토큰 배치 시작 →</button></div>`}
function setupView(){const q=state.setupQueue[state.setupIndex];return `<div class="panel-head"><div><div class="kicker">01 · 토큰 배치</div><h2>${q?`${q.token}번 토큰 · ${ORDER_TRACKS[q.track].name}`:'마지막 준비'}</h2><p class="lead">준비 표의 숫자만큼 각 명령 트랙에 번호 토큰을 위에서 아래 순서로 놓습니다.</p></div><span class="step-count">${state.setupIndex+1} / 6</span></div>${q?`<div class="row">${state.setupCard!==null?cardMarkup(state.nation,state.setupCard,'준비 카드'):backMarkup(state.nation)}<div class="decision"><h3>흰색 주사위로 시작 위치 결정</h3><p>${q.token}번 토큰을 ${ORDER_TRACKS[q.track].name} 트랙 첫 칸에서 오른쪽으로 이동합니다. 끝을 지나면 첫 칸으로 돌아옵니다.</p>${state.setupCard===null?'<div class="actions"><button class="primary" data-action="setupDraw">운명 카드 1장 뽑기</button></div>':`${diceDisplay(state.nation,state.setupCard,false)}<div class="actions"><button class="primary" data-action="setupMove">토큰 이동 완료 →</button></div>`}</div></div>`:`<div class="callout">번호 토큰 배치를 마쳤습니다. 봇 덱을 다시 모아 섞고 손패를 뒷면으로 뽑습니다. 행동 덱도 섞어 준비합니다. <strong>${state.firstPlayer==='player'?'플레이어':'봇'}가 첫 턴을 진행합니다.</strong></div><div class="actions"><button class="primary" data-action="setupFinish">준비 완료 → ${state.firstPlayer==='player'?'플레이어':'봇'} 턴</button></div>`}`}
function botReadyView(){return `<div class="panel-head"><div><div class="kicker">02 · 봇 턴</div><h2>${state.turn}번째 봇 활성화</h2><p class="lead">손패의 카드를 한 장씩 공개해 명령 판정을 합니다. 판정 실패 또는 손패 소진 시 턴을 종료합니다.</p></div><span class="step-count">손패 ${state.hand.length}장</span></div><div class="row">${backMarkup(state.nation)}<div class="decision"><h3>명령 판정 준비</h3><p>현재 목표값은 <strong>${ORDER_CHECK[state.orderIndex]}+</strong>입니다. 공개하면 카드의 흰색·빨간색 주사위 값이 자동으로 표시됩니다.</p><div class="actions"><button class="primary" data-action="orderDraw" ${!state.hand.length?'disabled':''}>손패 1장 공개 →</button>${!state.hand.length?'<button class="secondary" data-action="endTurn">활성화 종료 →</button>':''}</div></div></div>`}
function orderCheckView(){const target=ORDER_CHECK[state.orderIndex],{white,red}=diceForCard(state.nation,state.currentCard),passed=white>=target,next=passed?nextBotOrder(red):null;const preview=passed&&next?`<strong>성공 · ${next.name} 명령</strong><br>명령 판정 토큰을 다음 칸으로 옮깁니다. 빨간색 ${red}에 따라 ${red}번 토큰을 ${ORDER_TRACKS[next.track].name} 트랙에서 오른쪽으로 1칸 옮기면 <strong>${next.name}</strong>입니다.${next.special?' 특별 명령이므로 해당 행동 표도 판정합니다.':''} 실제 유닛과 대상은 플레이어가 결정합니다.`:`<strong>실패 · 봇 활성화 종료</strong><br>흰색 ${white}가 목표 ${target}+보다 작습니다. 공개한 카드를 버리고 명령 판정 토큰을 시작 칸으로 되돌린 뒤 손패를 보충합니다.`;return `<div class="panel-head"><div><div class="kicker">03 · 명령 판정</div><h2>흰색 주사위 ≥ ${target}?</h2><p class="lead">두 주사위 외의 카드 내용은 무시합니다. 흰색 값이 목표값 이상이면 성공합니다.</p></div><span class="step-count">규칙 §5</span></div><div class="row">${cardMarkup(state.nation,state.currentCard,'공개한 손패 카드')}<div class="decision"><h3>카드의 주사위 값</h3>${diceDisplay(state.nation,state.currentCard)}<div class="result ${passed?'':'bad'}">${preview}</div><div class="actions"><button class="primary" data-action="orderCheck">판정 확정 → ${passed?'명령 수행':'활성화 종료'}</button></div></div></div>`}
function orderExecuteView(){let o=state.activeOrder;return `<div class="panel-head"><div><div class="kicker">04 · 명령 수행</div><h2>${o.name} 명령</h2><p class="lead">빨간색 ${state.currentDice.red??state.currentDice.black}: ${o.token}번 토큰을 ${ORDER_TRACKS[o.track].name} 트랙에서 오른쪽으로 1칸 옮겼습니다.</p></div><span class="step-count">${o.pos+1} / ${ORDER_TRACKS[o.track].items.length}칸</span></div><div class="result"><strong>${o.name}</strong>${o.special?'<span class="tag" style="margin-left:9px">특별 명령</span>':''}<br>어떤 유닛이 어떻게 수행하는지는 플레이어가 결정합니다.</div>${o.special?'<div class="callout">색이 있는 칸입니다. 이 명령을 수행할 때 해당 행동 표 트리거를 판정합니다.</div>':''}<div class="actions">${o.special&&!o.specialChecked?`<button class="primary" data-action="orderSpecial">${o.name==='이동'?'특별 이동':'특별 사격'} 행동 판정 →</button>`:''}<button class="secondary" data-action="orderDone" ${o.special&&!o.specialChecked?'disabled':''}>명령 수행 완료 →</button><button class="danger" data-action="orderSkip">수행 불가 / 부적절 → 행동 트랙 ↓</button></div><p class="hint">수행할 수 없거나 봇에게 타당하지 않은 명령은 행동 트랙 토큰을 아래로 1칸 옮깁니다.</p>`}
function actionView(){let a=state.action,t=TRIGGERS.find(x=>x.id===a.triggerId);let head=`<div class="panel-head"><div><div class="kicker">05 · 행동 판정</div><h2>${t.name}</h2><p class="lead">트리거가 발생하면 행동 덱에서 반드시 1장을 뽑습니다. 흰색 6이면 이 판정을 마친 뒤 한 번 더 판정합니다.</p></div><span class="step-count">규칙 §7</span></div>`;
 if(a.phase==='draw')return head+`<div class="row">${backMarkup(state.actionNation)}<div class="decision"><h3>행동 트랙 목표 ${ACTION_CHECK[state.actionIndex]}+</h3><p>카드의 두 주사위만 사용합니다. 행동 덱이 바닥나면 버린 카드를 섞어 새 덱으로 만듭니다.</p><div class="actions"><button class="primary" data-action="actionDraw">행동 카드 1장 뽑기 →</button></div></div></div>`;
 if(a.phase==='check')return head+`<div class="row">${cardMarkup(state.actionNation,a.card,'행동 판정 카드')}<div class="decision"><h3>카드의 주사위 값</h3>${diceDisplay(state.actionNation,a.card)}<div class="actions"><button class="primary" data-action="actionCheck">흰색 ${ACTION_CHECK[state.actionIndex]}+ 판정 →</button></div></div></div>`;
 if(a.phase==='select')return head+`<div class="result">트랙 판정 성공 · 빨간색 <strong>${a.red??a.black}</strong>${a.white===6?' · 추가 판정 예약':''}</div><h3>특별 행동을 선택하세요</h3><p class="hint">표에서 봇의 특별 사격은 플레이어가 행동을 선택합니다. 요구 조건과 실제 상황을 고려하세요.</p><div class="choice-grid">${t.actions.map((x,i)=>`<button class="choice-card" data-action="selectAction" data-index="${i}"><strong>${x[1]}</strong><span>${x[2]} · ${x[3]}</span></button>`).join('')}</div>`;
 if(a.phase==='requirements'){let x=t.actions[a.selected];return head+`<div class="row">${cardMarkup(state.actionNation,a.card,'트랙 판정 카드')}<div class="decision"><h3>${x[1]}</h3><p>빨간색 ${a.red??a.black} · 행동 선택 범위 ${x[0]}</p><div class="result"><strong>요구 조건</strong><br>${x[2]}</div><p>조건을 충족하면 행동 덱에서 새 카드 1장을 뽑아 목표값을 판정합니다. 충족하지 못하면 이번 판정은 종료됩니다.</p><div class="actions"><button class="primary" data-action="requirementsYes">조건 충족 → 목표값 판정</button><button class="secondary" data-action="requirementsNo">조건 미충족 → 종료</button></div></div></div>`}
 if(a.phase==='target'){let x=t.actions[a.selected];return head+`<div class="row">${cardMarkup(state.actionNation,a.targetCard,'목표값 판정 카드')}<div class="decision"><h3>${x[1]} · 목표값 ${actionTarget(x)}+</h3><p>새 카드의 흰색 주사위 값으로 판정합니다. 성공하면 행동 트랙 토큰을 맨 위 칸으로 되돌리고 반드시 행동을 수행합니다.</p>${diceDisplay(state.actionNation,a.targetCard,false)}<div class="actions"><button class="primary" data-action="targetCheck">목표값 판정 →</button></div></div></div>`}
 if(a.phase==='result'){let x=t.actions[a.selected];return head+`<div class="result ${a.passed?'':'bad'}"><strong>${a.passed?`${x[1]} 사용`:'목표값 판정 실패'}</strong><br>${a.passed?'행동 트랙을 맨 위로 되돌렸습니다. 실제 대상과 최적 사용 시점은 플레이어가 정합니다.':'이번 행동 판정은 종료됩니다.'}</div>${t.id==='time'?'<div class="callout">Dig-In 판정을 마친 뒤 행동 덱을 섞습니다.</div>':''}<div class="actions"><button class="primary" data-action="actionFinish">${a.extra?'추가 행동 판정 →':'이전 단계로 →'}</button></div>`}
 return head+`<div class="result bad"><strong>이번 행동 판정 종료</strong><br>${a.white===6?'추가 행동 판정을 진행합니다.':'표에 따라 더 이상 진행하지 않습니다.'}</div><div class="actions"><button class="primary" data-action="actionFinish">${a.extra?'추가 행동 판정 →':'이전 단계로 →'}</button></div>`
}
function playerView(){let fireToken=state.tokenPositions.some(x=>ORDER_TRACKS[x.track].special?.includes(x.pos)&&ORDER_TRACKS[x.track].items[x.pos]==='사격'),firstTurn=state.firstPlayer==='player'&&state.turn===0;return `<div class="panel-head"><div><div class="kicker">06 · 플레이어 턴</div><h2>${firstTurn?'첫 턴 · 플레이어 선공':'상대 트리거 확인'}</h2><p class="lead">플레이어 턴은 기본 게임대로 진행합니다. 표의 트리거가 발생하면 각각 행동 판정을 합니다.</p></div><span class="step-count">규칙 §9</span></div><div class="callout">이동 명령이면 (1) 숨겨진 지뢰·철조망과 (2) 기회 사격을 <strong>별도 판정</strong>으로 확인하세요. 전진 명령에는 (1)만 해당합니다.</div><div class="choice-grid">${TRIGGERS.filter(t=>!t.id.startsWith('bot')).map(t=>`<button class="choice-card" data-action="trigger" data-trigger="${t.id}"><strong>${t.name}</strong><span>${t.actions.map(a=>a[1]).join(' · ')}</span></button>`).join('')}${fireToken?'<button class="choice-card" data-action="trigger" data-trigger="botFire"><strong>기회 사격 중 특별 사격</strong><span>특별 사격 칸의 토큰이 기회 사격에 해당할 때</span></button>':''}</div><div class="divider"></div><div class="actions"><button class="secondary" data-action="discardHand" ${!state.hand.length?'disabled':''}>이벤트로 봇 손패 1장 버리기</button><button class="primary" data-action="nextBotTurn">${firstTurn?'첫 플레이어 턴':'플레이어 턴'} 완료 → ${firstTurn?'첫 ':''}봇 턴</button></div><p class="hint">봇 손패를 버려야 하는 이벤트가 생기면 뒷면 손패 더미에서 버립니다. 행동 사용 시점은 플레이어가 정합니다.</p>`}
function actionTableView(){
 const onlyCurrent=state.actionTableMode==='current';
 const triggers=onlyCurrent?TRIGGERS.filter(trigger=>trigger.id===state.action?.triggerId):TRIGGERS;
 const rows=triggers.map(trigger=>{const selected=state.action?.selected;const actions=onlyCurrent&&Number.isInteger(selected)&&trigger.actions[selected]?[trigger.actions[selected]]:trigger.actions;return `<tbody class="action-group ${state.action?.triggerId===trigger.id?'current':''}">${actions.map((action,index)=>`<tr>${index===0?`<th scope="rowgroup" rowspan="${actions.length}">${trigger.name}</th>`:''}<td>${action[0]}</td><td class="action-name">${action[1]}</td><td>${action[2]}</td><td>${action[1]==='Op-Fire'?'정찰 6+ (미국 5+) · 공격자 6+ · 방어자 5+ (미국 4+)':action[3]}</td></tr>`).join('')}</tbody>`}).join('');
 const table=rows?`<div class="table-wrap"><table class="action-table"><thead><tr><th scope="col">트리거</th><th scope="col">빨간색 선택값</th><th scope="col">행동</th><th scope="col">필요 조건</th><th scope="col">목표값</th></tr></thead>${rows}</table></div>`:'<p class="action-empty">현재 진행 중인 행동 판정이 없습니다. 전체 보기를 선택하면 행동 표를 볼 수 있습니다.</p>';
 return `<section class="action-reference" aria-labelledby="actionTableTitle"><div class="track-label"><span id="actionTableTitle">행동 표</span><a href="CCBot_V3.0_Actions.jpg" target="_blank" rel="noopener">원본 행동 표 ↗</a></div><div class="track-mode" role="group" aria-label="행동 표 표시 방식"><button type="button" data-action="actionTableMode" data-mode="current" aria-pressed="${onlyCurrent}">현재 항목만</button><button type="button" data-action="actionTableMode" data-mode="all" aria-pressed="${!onlyCurrent}">전체 보기</button></div><p class="hint">흰색 주사위로 상단의 행동 판정 트랙을 확인하고, 성공하면 빨간색 주사위로 행동을 고릅니다. 특별 사격은 플레이어가 행동을 선택합니다.</p>${table}</section>`
}
function tracksView(){
 const orders=ORDER_TRACKS.map((t,i)=>`<div class="order-track"><span class="order-track-name">${i+1}. ${t.name}</span><div class="track">${t.items.map((name,j)=>{let tokens=state.tokenPositions.filter(p=>p.track===i&&p.pos===j);return `<div class="track-cell ${t.special?.includes(j)?'special':''}" title="${name}">${name}${tokens.map(z=>`<span class="token">${z.token}</span>`).join('')}</div>`}).join('')}</div></div>`).join('');
 return `<div class="panel-head"><div><div class="kicker">보드 현황</div><h2>판정 트랙과 번호 토큰</h2></div><a href="CCBot_V3.0_Board.jpg" target="_blank" rel="noopener" class="mini">원본 보드 보기 ↗</a></div><div class="track-group"><div><div class="track-label"><span>명령 판정 트랙</span><span>현재 ${ORDER_CHECK[state.orderIndex]}+</span></div><div class="track">${ORDER_CHECK.map((n,i)=>`<div class="track-cell ${i===state.orderIndex?'active':''}">${n}+<small>${i===0?'A/R':i===1?'D':i===2?'FR':''}</small></div>`).join('')}</div></div><div><div class="track-label"><span>행동 판정 트랙</span><span>현재 ${state.actionIndex+1} / ${ACTION_CHECK.length}칸 · ${ACTION_CHECK[state.actionIndex]}+</span></div><div class="track" data-action-track="true">${ACTION_CHECK.map((n,i)=>`<div class="track-cell ${i===state.actionIndex?'active':''} ${i>5?'stop':''}">${n}+<small>${i===5?'R/D':i===8?'A':''}</small></div>`).join('')}</div></div><div><div class="track-label"><span>명령 트랙</span><span>초록색은 특별 명령</span></div><div class="orders">${orders}</div></div>${actionTableView()}</div>`
}
function referenceView(){return `<a href="Combat%20Commander%20Bot%20-%20Solo%20Rules_3.1_KO.pdf" target="_blank" rel="noopener">한국어 규칙 PDF ↗</a><a href="CCBot_V3.0_Board.jpg" target="_blank" rel="noopener">명령 보드 ↗</a><a href="CCBot_V3.0_Actions.jpg" target="_blank" rel="noopener">행동 표 ↗</a><span>주도권 §10: 봇은 가능하면 보유하고 돌연 종료에서는 유리하게 사용합니다. 사용 여부는 플레이어가 판단합니다.</span><span>규칙서의 검은색 주사위는 카드 그림의 빨간색 주사위입니다. 행동 이름은 제공된 영문 표기를 유지했습니다.</span>${state.log.length?`<details><summary>진행 기록</summary><ol class="log">${state.log.slice(0,30).map(x=>`<li>${e(x)}</li>`).join('')}</ol></details>`:''}`}
function render(){const nav=state.firstPlayer==='player'?[['준비','config'],['플레이어 턴','player'],['봇 턴','botReady'],['명령 판정','orderCheck'],['명령 수행','orderExecute'],['행동 판정','action'],['시간 절차','time'],['게임 종료','gameOver']]:[['준비','config'],['봇 턴','botReady'],['명령 판정','orderCheck'],['명령 수행','orderExecute'],['행동 판정','action'],['시간 절차','time'],['플레이어 턴','player'],['게임 종료','gameOver']];$('#phaseNav').innerHTML=nav.map(([name,key],i)=>`<div class="phase-item ${key===state.stage||key==='config'&&state.stage==='setup'?'active':key==='config'?'done':''}"><span class="number">${i+1}</span>${name}</div>`).join('');$('#mainPanel').innerHTML=({config:configView,setup:setupView,botReady:botReadyView,orderCheck:orderCheckView,orderExecute:orderExecuteView,action:actionView,time:timeView,player:playerView,gameOver:gameOverView})[state.stage]();$('#trackPanel').innerHTML=tracksView()+(['botReady','orderCheck','orderExecute'].includes(state.stage)?`<div class="divider"></div><div class="track-label"><span>진행 중 발생한 트리거</span><span>해당할 때만 판정</span></div><div class="actions">${TRIGGERS.filter(t=>['melee','winMelee','break','time'].includes(t.id)).map(t=>`<button class="secondary" data-action="trigger" data-trigger="${t.id}">${t.name}</button>`).join('')}</div>`:'');$('#referencePanel').innerHTML=referenceView();$('#undoBtn').disabled=!history.length;}
document.addEventListener('click',ev=>{let b=ev.target.closest('[data-action]');if(!b)return;let act=b.dataset.action;notice('');switch(act){
 case 'actionTableMode':{const mode=b.dataset.mode;if(!['current','all'].includes(mode)||state.actionTableMode===mode)break;commit(()=>{state.actionTableMode=mode});break}
 case 'startSetup':{let n=$('#nation').value,p=$('#posture').value,an=$('#actionNation').value,first=$('#firstPlayer').value,ol=Number($('#orderLimit').value),hl=Number($('#handLimit').value);if(!Number.isInteger(ol)||ol<1||!Number.isInteger(hl)||hl<1){notice('명령 한도와 손패 한도를 1 이상의 정수로 입력하세요.');return}commit(()=>{state.nation=n;state.posture=p;state.actionNation=an;state.firstPlayer=first;state.orderLimit=ol;state.handLimit=hl;initGame()},'봇 준비 시작');break}
 case 'setupDraw':commit(()=>{state.setupCard=drawBot()},'준비 카드 공개');break;
 case 'setupMove':{let w=diceForCard(state.nation,state.setupCard).white;commit(()=>{let x=state.tokenPositions[state.setupIndex];x.pos=(w-1)%ORDER_TRACKS[x.track].items.length;state.botDiscard.push(state.setupCard);state.setupCard=null;state.setupIndex++},`준비 토큰 이동: 흰색 ${w}`);break}
 case 'setupFinish':commit(finishSetup);break;
 case 'orderDraw':commit(()=>{state.currentCard=state.hand.shift();state.stage='orderCheck'},'손패 공개');break;
 case 'orderCheck':{let {white,red}=diceForCard(state.nation,state.currentCard),next=white>=ORDER_CHECK[state.orderIndex]?nextBotOrder(red):null;if(white>=ORDER_CHECK[state.orderIndex]&&!next){notice('해당 번호 토큰을 찾을 수 없습니다. 저장 상태를 확인하세요.');break}commit(()=>{state.currentDice={white,red};state.botDiscard.push(state.currentCard);if(white<ORDER_CHECK[state.orderIndex]){state.stage='botReady';endTurn()}else{state.orderIndex=Math.min(state.orderIndex+1,ORDER_CHECK.length-1);state.tokenPositions.find(x=>x.token===red).pos=next.pos;state.activeOrder=next;state.stage='orderExecute'}},`명령 판정: 흰색 ${white}, 빨간색 ${red}`);break}
 case 'orderDone':commit(()=>{state.currentCard=null;state.currentDice=null;state.activeOrder=null;if(state.hand.length)state.stage='botReady';else endTurn()},'명령 수행 완료');break;
 case 'orderSkip':commit(()=>{state.actionIndex=Math.min(state.actionIndex+1,ACTION_CHECK.length-1);state.currentCard=null;state.currentDice=null;state.activeOrder=null;if(state.hand.length)state.stage='botReady';else endTurn()},'명령 수행 불가: 행동 트랙 1칸 아래');break;
 case 'orderSpecial':commit(()=>{state.activeOrder.specialChecked=true;startAction(state.activeOrder.name==='이동'?'botMove':'botFire','orderExecute')},'특별 명령 행동 판정 시작');break;
 case 'endTurn':commit(endTurn,'봇 활성화 종료');break;
 case 'actionDraw':commit(()=>{state.action.card=drawAction();state.action.phase='check'},'행동 카드 공개');break;
 case 'actionCheck':{let {white,red}=diceForCard(state.actionNation,state.action.card);commit(()=>{let a=state.action,t=TRIGGERS.find(x=>x.id===a.triggerId);a.white=white;a.red=red;state.actionDiscard.push(a.card);if(white===6)a.extra++;if(white<ACTION_CHECK[state.actionIndex]){state.actionIndex=Math.min(state.actionIndex+1,ACTION_CHECK.length-1);a.phase='ended'}else{let pick=pickAction(t,red);if(pick===null)a.phase='select';else{a.selected=pick;a.phase='requirements'}}},`행동 트랙 판정: 흰색 ${white}, 빨간색 ${red}`);break}
 case 'selectAction':commit(()=>{state.action.selected=Number(b.dataset.index);state.action.phase='requirements'},'특별 사격 행동 선택');break;
 case 'requirementsYes':commit(()=>{let c=drawAction();if(c===null){notice('행동 덱이 비어 있습니다.');return}state.action.targetCard=c;state.action.phase='target'},'행동 조건 충족');break;
 case 'requirementsNo':commit(()=>{state.action.phase='ended'},'행동 조건 미충족');break;
 case 'targetCheck':{let white=diceForCard(state.actionNation,state.action.targetCard).white;commit(()=>{let a=state.action,t=TRIGGERS.find(x=>x.id===a.triggerId),x=t.actions[a.selected];a.passed=white>=actionTarget(x);state.actionDiscard.push(a.targetCard);a.phase='result';if(a.passed)state.actionIndex=0},`행동 목표값 판정: 흰색 ${white}`);break}
 case 'actionFinish':commit(()=>{let a=state.action;if(a.triggerId==='time'){state.actionDeck=shuffle([...state.actionDeck,...state.actionDiscard]);state.actionDiscard=[]}finishAction()},'행동 판정 완료');break;
 case 'timeNext':if(state.time.step===2){notice('현재 시간 칸과 돌연 종료 굴림을 먼저 확인하세요.');break}commit(()=>{let step=state.time.step;if(step===1){state.botDeck=shuffle([...state.botDeck,...state.botDiscard]);state.botDiscard=[]}if(step<6){state.time.step++}else{const resume=state.time.resume;state.time=null;if(resume==='endTurn')refillBotHand();else state.stage=resume}},'시간 절차 단계 완료');break;
 case 'timeCheck':{const current=Number($('#currentSpace').value),sudden=Number($('#suddenSpace').value);if($('#currentSpace').value===''||$('#suddenSpace').value===''||!Number.isInteger(current)||current<0||!Number.isInteger(sudden)||sudden<0){notice('두 마커가 놓인 칸의 숫자를 0 이상의 정수로 입력하세요.');break}if(current<sudden){commit(()=>{state.time.currentSpace=current;state.time.suddenSpace=sudden;state.time.step=3},'현재 시간 칸이 돌연 종료 마커 전이므로 굴림 생략');break}if(!state.botDeck.length){notice('돌연 종료 굴림을 위한 봇 운명 덱이 비었습니다.');break}commit(()=>{const card=drawBot(),{white,red}=diceForCard(state.nation,card),total=white+red;state.botDiscard.push(card);state.time.currentSpace=current;state.time.suddenSpace=sudden;state.time.suddenRoll={card,white,red,total};state.time.initiativeHolder=null;state.log.unshift(`돌연 종료 굴림: ${current}칸, ${white}+${red}=${total} · 주도권 확인 대기`)});break}
 case 'timeInitiativeReroll':{if(state.stage!=='time'||state.time.step!==2||!state.time.suddenRoll)break;const holder=$('#initiativeHolder').value;if(!['bot','player'].includes(holder)){notice('실제 주도권 카드 보유자를 선택하세요.');break}if(!state.botDeck.length){notice('다시 굴릴 봇 운명 덱이 비었습니다.');break}commit(()=>{const card=drawBot(),{white,red}=diceForCard(state.nation,card),total=white+red;state.botDiscard.push(card);state.time.suddenRoll={card,white,red,total};state.time.initiativeHolder=holder==='bot'?'player':'bot';state.log.unshift(`주도권 사용: ${holder==='bot'?'봇':'플레이어'} → ${holder==='bot'?'플레이어':'봇'} · 돌연 종료 재굴림 ${white}+${red}=${total}`)});break}
 case 'timeApplyRoll':{if(state.stage!=='time'||state.time.step!==2||!state.time.suddenRoll)break;const total=state.time.suddenRoll.total,current=state.time.currentSpace;commit(()=>{if(total<current)state.stage='gameOver';else state.time.step=3},total<current?'주도권 확인 후 돌연 종료 결과 확정':'주도권 확인 후 돌연 종료를 넘기고 시간 절차 진행');break}
 case 'timeDigIn':commit(()=>{state.time.botDigInDone=true;startAction('time','time')},'TIME! 트리거: 봇 진지 구축 행동 판정 시작');break;
 case 'trigger':commit(()=>startAction(b.dataset.trigger,state.stage),'행동 트리거: '+b.textContent.trim());break;
 case 'discardHand':commit(()=>{state.botDiscard.push(state.hand.shift())},'이벤트로 봇 뒷면 손패 1장 버림');break;
 case 'nextBotTurn':commit(()=>{state.turn++;state.stage='botReady'},'다음 봇 턴 시작');break;
 }});
function endTurn(){state.orderIndex=state.nation==='French'?2:POSTURES[state.posture].order;state.currentCard=null;state.currentDice=null;state.activeOrder=null;refillBotHand()}
$('#undoBtn').addEventListener('click',async()=>{if(!history.length||busy)return;busy=true;const before=structuredClone(state),oldHistory=structuredClone(history);try{state=history.pop();correctOldSave(state);recoverOldTime(state);await persist();render();notice('직전 단계를 취소했습니다.')}catch(error){state=before;history=oldHistory;render();notice('실행 취소 저장 실패: '+error.message)}finally{busy=false}});
$('#newBtn').addEventListener('click',async()=>{if(busy||!store)return;busy=true;const old={state,history,saveId,revision};try{state=fresh();history=[];saveId=null;revision=-1;await persist();render();notice('새 게임 설정을 시작합니다. 이전 게임은 “저장된 게임”에서 다시 열 수 있습니다.')}catch(error){state=old.state;history=old.history;saveId=old.saveId;revision=old.revision;render();notice('새 게임 저장 실패: '+error.message)}finally{busy=false}});
$('#exportBtn').addEventListener('click',()=>{let blob=new Blob([JSON.stringify({app:'CCBOT-KO',version:2,state,history},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`ccbot-save-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)});
$('#savedBtn').addEventListener('click',async()=>{if(!store)return;try{let saves=await store.listing();$('#savedList').innerHTML=saves.length?saves.map(s=>`<button class="saved-entry" data-save-id="${s.id}"><strong>${NATIONS[s.nation]||s.nation} · ${s.turn===0?'플레이어 선공 · 첫 봇 턴 전':`봇 턴 ${s.turn}`}</strong><small>${new Date(s.updatedAt).toLocaleString('ko-KR')} · ${s.stage}</small></button>`).join(''):'<p class="empty">저장된 게임이 없습니다.</p>';$('#savedDialog').showModal()}catch(error){notice('목록을 열 수 없습니다: '+error.message)}});
$('#closeSaved').addEventListener('click',()=>$('#savedDialog').close());
$('#savedList').addEventListener('click',async ev=>{const b=ev.target.closest('[data-save-id]');if(!b||busy)return;busy=true;try{let data=await store.read(b.dataset.saveId);state=data.state;history=data.history;saveId=data.id;revision=data.revision;const backsCorrected=correctOldSave(state),timeRecovered=recoverOldTime(state);if(backsCorrected||timeRecovered)await persist();try{localStorage.setItem(STORE,saveId)}catch{}$('#savedDialog').close();$('#saveStatus').textContent=`JSON 저장됨 · r${revision}`;render();notice('저장된 게임을 불러왔습니다.')}catch(error){notice('불러오기 실패: '+error.message)}finally{busy=false}});
$('#importInput').addEventListener('change',async ev=>{let f=ev.target.files[0];ev.target.value='';if(!f||busy||!store)return;busy=true;const old={state,history,saveId,revision};try{let x=JSON.parse(await f.text()),s=x.state;if(x.app!=='CCBOT-KO'||s?.version!==1||!NATIONS[s.nation]||!POSTURES[s.posture]||!Array.isArray(s.tokenPositions)||!Array.isArray(s.hand)||!Array.isArray(s.botDeck))throw Error('지원하지 않는 저장 파일입니다.');state=s;history=Array.isArray(x.history)?x.history:[];correctOldSave(state);recoverOldTime(state);saveId=null;revision=-1;await persist();render();notice('저장 파일을 별도 게임으로 불러왔습니다.')}catch(error){state=old.state;history=old.history;saveId=old.saveId;revision=old.revision;render();notice('불러오기 실패: '+error.message)}finally{busy=false}});
async function init(){try{store=await JsonStore.open();let last;try{last=localStorage.getItem(STORE)}catch{}let data;if(last){try{data=await store.read(last)}catch{}}if(!data){let all=await store.listing();if(all.length)data=await store.read(all[0].id)}if(data){state=data.state;history=data.history;saveId=data.id;revision=data.revision;const backsCorrected=correctOldSave(state),timeRecovered=recoverOldTime(state);if(backsCorrected||timeRecovered)await persist();$('#saveStatus').textContent=`JSON 저장됨 · r${revision}`}else{state=fresh();await persist()}render()}catch(error){state=fresh();render();notice('JSON 저장소를 열 수 없습니다: '+error.message);$('#saveStatus').textContent='저장소 사용 불가'}}
init();
