"""Build a self-contained Pages artifact. Never publish data/sessions or private files."""
import json
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from cdg.games.paths_of_glory import CARDS, DICE


def build(destination=None):
    cards = {key: {**card, 'image': card['image'].lstrip('/')} for key, card in CARDS.items()}
    (ROOT / 'web/games/pog-data.js').write_text(
        '// Generated by scripts/build_static.py; card metadata and official rule table.\n'
        + 'export const CARDS = ' + json.dumps(cards, ensure_ascii=False) + ';\n'
        + 'export const DICE = ' + json.dumps(DICE, ensure_ascii=False) + ';\n', encoding='utf-8')
    (ROOT / 'web/rules').mkdir(exist_ok=True)
    for source in (ROOT / 'images').glob('*.pdf'):
        shutil.copy2(source, ROOT / 'web/rules' / source.name)
    (ROOT / 'web/.nojekyll').touch()
    if destination:
        target = Path(destination).resolve()
        if target.exists():
            raise SystemExit('Use a new/empty artifact path; existing directories are not overwritten.')
        shutil.copytree(ROOT / 'web', target)
    print(f'Static site ready: {destination or ROOT / "web"}')


if __name__ == '__main__':
    build(sys.argv[1] if len(sys.argv) > 1 else None)
