import {FileStore} from './storage.js';
let store;
'use strict';
const $ = s => document.querySelector(s);
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const attr = obj => esc(JSON.stringify(obj));
const sides = {cp:'동맹군', ap:'연합군'};
const stages = {mobilization:'동원전', limited:'제한전', total:'총력전'};
const modes = {ops:'작전', event:'이벤트', sr:'전략적 재배치', rp:'충원'};
const phaseNames = {action:'행동 페이즈',resolve:'카드 효과 해결',draw:'전략 카드 받기'};
const viewNames = {table:'플레이 테이블',rules:'룰북 & 가이드',history:'플레이 기록',llm:'LLM 함께하기'};
let session=null, game=null, catalog={}, currentView='table', selected=null, busy=false, proposal=null, llmContext=null;
let toastTimer;
function toast(text,error=false){const el=$('#toast');el.textContent=text;el.classList.toggle('error',error);el.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.hidden=true,error?10000:4500);}
async function api(path,body){return store.request(path,body);}
function status(text,error=false){$('#save-status').classList.toggle('error',error);$('#save-status').replaceChildren();const dot=document.createElement('span');dot.className='tiny-dot';$('#save-status').append(dot,document.createTextNode(text));}
function saved(){$('#export-save').disabled=!session;status(session?`브라우저 JSON 저장됨 · r${session.revision} · ${new Date(session.updated_at).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'})}`:'브라우저 저장 준비');}
function remember(id){try{localStorage.setItem('cdg-session:'+location.pathname,id);}catch{/* Disk-backed sessions remain available without localStorage. */}}
function setBusy(value){busy=value;document.body.classList.toggle('busy',value);document.body.setAttribute('aria-busy',String(value));}
async function act(action,revision=session?.revision){if(busy||!session)return;setBusy(true);status('JSON 파일에 저장 중…');try{session=await api(`/api/sessions/${session.id}/actions`,{expected_revision:revision,action});selected=null;llmContext=null;render();saved();toast(session.history.at(-1).message);}catch(e){status('저장되지 않음 · 다시 시도하세요',true);toast(e.message,true);if(e.status===409){try{session=await api(`/api/sessions/${session.id}`);selected=null;render();saved();}catch{}}}finally{setBusy(false);}}
const button=(label,action,cls='secondary')=>`<button class="${cls}" data-action="${attr(action)}">${label}</button>`;
function heading(eyebrow,title,description,buttons=''){return `<div class="page-heading"><div><span class="eyebrow">${eyebrow}</span><h1>${esc(title)}</h1><p class="muted">${esc(description)}</p></div><div class="heading-right">${buttons}</div></div>`;}
function emptySession(){return `<div class="large-empty"><span class="eyebrow">YOUR TABLE AWAITS</span><h2>먼저 게임을 시작해 주세요.</h2><p>준비를 마치면 모든 선택과 진행 상황이 JSON에 저장됩니다.</p><button class="primary new-game">새 게임 시작 →</button></div>`;}
function welcome(){return heading('THE ART OF PLAYING BOTH SIDES','나만의 전략 테이블','CDG 솔로 시스템으로 시작하는 한 사람의 캠페인.')+`<section class="welcome"><div><span class="eyebrow">PATHS OF GLORY · 1914—1918</span><h1>두 진영의 선택,<br>하나의 테이블.</h1><p>운명 주사위가 선택지를 열고,<br>당신의 판단이 다음 역사를 만듭니다.</p><button class="primary new-game">첫 번째 게임 시작 <span>→</span></button></div><div class="welcome-art" aria-hidden="true"><img src="./assets/cards/cp-01.webp" alt=""><img src="./assets/cards/ap-01.webp" alt=""></div></section><section class="welcome-features"><div><span class="feature-num">01</span><b>룰북을 따라가는 선택</b><p>공통 규칙과 게임별 플레이시트에 따라 가능한 카드를 안내합니다.</p></div><div><span class="feature-num">02</span><b>매 선택이 남는 기록</b><p>주사위, 카드 사용, 페이즈 진행을 브라우저 전용 JSON 파일에 자동 보관합니다. 내보내기로 백업하세요.</p></div><div><span class="feature-num">03</span><b>LLM과 함께하는 판단</b><p>공개된 상황을 공유하고, LLM이 제안한 선택을 확인해 적용하세요.</p></div></section>`;}
function render(){
 $('#page-title').textContent=viewNames[currentView];document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===currentView));
 const main=$('#main');
 if(currentView==='rules')main.innerHTML=rulesView();
 else if(!session)main.innerHTML=currentView==='table'?welcome():emptySession();
 else if(currentView==='table')main.innerHTML=tableView();
 else if(currentView==='history')main.innerHTML=historyView();
 else {main.innerHTML=llmView();loadLLM();}
}
function tableView(){const s=session.state;const active=s.battle?.side||s.active;const round=Math.min(6,s.rounds[s.active]+1);
 return heading('SOLO CAMPAIGN / 01','패스 오브 글로리',session.name,`<button class="secondary" data-view="rules">▤ 룰북 보기</button>`)+
 `<section class="status-strip" aria-label="게임 진행 상태"><div><span class="status-label">GAME TURN</span><span class="status-value">${String(s.turn).padStart(2,'0')} <small>턴</small></span></div><div><span class="status-label">ACTION ROUND</span><span class="status-value">${round} <small>/ 6 라운드</small></span><div class="round-track">${Array.from({length:6},(_,i)=>`<i class="${i<s.rounds[s.active]?'done':i===s.rounds[s.active]?'current':''}"></i>`).join('')}</div></div><div><span class="status-label">CURRENT PHASE</span><span class="status-value">${s.battle?'전투 카드 선택':phaseNames[s.phase]}</span></div><div><span class="status-label">ACTIVE SIDE</span><span class="status-value">${s.phase==='draw'?'양 진영':sides[active]} <small>${s.phase==='draw'?'다음 턴 준비':s.battle?s.battle.step==='attacker'?'공격자':'방어자':'선택 대기'}</small></span></div></section>`+
 `<div class="table-layout"><div class="boards">${board('cp')}${board('ap')}</div><aside class="inspector-column" aria-label="진행 및 카드 선택"><section class="panel">${actionPanel()}</section><section class="panel" id="inspector">${inspector()}</section></aside></div>`+
 `<section class="activity-panel"><div class="section-heading"><h3>테이블 기록</h3><button class="text-button" data-view="history">전체 기록 보기 ↗</button></div>${logRows(session.history.slice(-3).reverse())}<form class="note-form" id="note-form"><input name="note" aria-label="게임판 상황 메모" maxlength="4000" required placeholder="게임판 상황, 전투 결과, 선택 이유를 기록하세요…"><button class="secondary" type="submit">메모 저장 ＋</button></form></section>`;
}
function board(side){const s=session.state,p=s.sides[side],active=(s.battle?.side||s.active)===side&&s.phase!=='draw';
 const tools=s.available_actions.filter(a=>a.type==='reshuffle'&&a.side===side);
 return `<section class="board ${side} ${active?'active':''}" aria-label="${sides[side]} 카드 디스플레이"><div class="board-head"><div class="side-title"><span class="side-emblem">${side==='cp'?'✠':'✦'}</span><div><h3>${sides[side]}</h3><small>${side==='cp'?'CENTRAL POWERS':'ALLIED POWERS'}</small></div><span class="active-label">${active?'● 활성 진영':'대기'}</span></div><div class="board-meters"><span>남은 카드 <b class="remaining">${p.remaining}</b><span class="limit"> / ${s.max_hand}</span></span></div></div><div class="official-mat"><div class="track-markers" aria-label="남은 카드 ${p.remaining}, 최대 핸드 ${s.max_hand}"><span class="track-marker max-marker" style="--position:${s.max_hand}" title="최대 핸드 ${s.max_hand}"><span class="marker-label">최대 </span>${s.max_hand}</span><span class="track-marker remaining-marker" style="--position:${p.remaining}" title="남은 카드 ${p.remaining}"><span class="marker-label">남음 </span>${p.remaining}</span></div><div class="card-row">${'ABCDE'.split('').map(slot=>slotView(side,slot)).join('')}</div></div><div class="board-foot"><span>받기 더미 <b>${p.deck_count}</b>장</span><button class="text-button" data-pile="${side}:discard">버림 ${p.discard.length}</button><button class="text-button" data-pile="${side}:removed">제거 ${p.removed.length}</button><span>${stages[p.stage]} · ${s.rounds[side]}/6 행동 완료</span></div>${tools.length?`<div class="side-tools">${tools.map(a=>a.reason==='war'?`<button class="secondary" data-war="${side}" data-stage="${a.stage}">${stages[a.stage]} 진입 / 다시 섞기 ↗</button>`:button('고갈: 버린 더미 다시 섞기',a)).join('')}</div>`:''}</section>`;
}
function slotView(side,slot){const s=session.state,d=s.sides[side].display[slot],c=d?.card;
 const canReveal=s.available_actions.some(a=>a.type==='reveal'&&s.active===side&&a.slot===slot);
 const eligible=s.candidates.some(x=>s.active===side&&x.slot===slot)||s.available_actions.some(a=>(a.type==='combat_play'&&s.battle?.side===side||a.type==='draw_discard'&&a.side===side)&&a.slot===slot);
 const isSelected=selected?.side===side&&selected?.slot===slot;
 const back=`<div class="card-back"><span class="back-border"></span><span class="back-corner">✦</span><div class="back-center"><div class="back-symbol">✥</div><span>PATHS OF GLORY</span><small>CDG SOLO</small></div></div>`;
 return `<div class="slot ${eligible?'eligible':''} ${isSelected?'selected':''}"><div class="slot-label"><b>${slot}</b><span class="slot-status">${eligible?'선택 가능':slot==='C'?'받기 더미':c?'앞면':'뒷면'}</span></div><button class="card-button" ${canReveal?`data-action="${attr({type:'reveal',slot})}"`:`data-inspect="${side}:${slot}"`} aria-label="${sides[side]} ${slot} 슬롯: ${c?esc(c.name):d?canReveal?'클릭하여 공개':'뒷면 카드':'빈 슬롯'}" ${!d?'disabled':''}>${c?`<img src="${esc(c.image)}" alt="${esc(c.name)}" loading="lazy">`:d?back:'<span class="card-empty"><b>＋</b>빈 슬롯</span>'}</button><div class="card-caption"><span>${c?`#${String(c.number).padStart(2,'0')}`:d?canReveal?'공개할 카드 선택':'비공개':'—'}</span><span class="ops ${c?.combat?'badge-cc':''}">${c?`${c.combat?'CC · ':''}${c.ops} OPS`:slot==='C'?'DRAW PILE':''}</span></div></div>`;
}
const dieLabels=['C · 최저 작전값 · !!','이벤트 · 최저 작전값','ABC','AB','CDE','DE'];
function dieFace(value){return `<span class="fate-face face-${value}" role="img" aria-label="운명 주사위 ${value}: ${dieLabels[value-1]}"></span>`;}
function actionPanel(){const s=session.state,p=s.pending;
 let content='<div class="panel-label">이번 행동<small>FATE & CHOICE</small></div>';
 if(s.battle){const b=s.battle;return content+`<div class="battle-banner">${sides[b.side]} · ${b.step==='attacker'?'공격자 먼저':'방어자 차례'}</div><p class="instruction">사용 조건을 만족하는 앞면 전투 카드를 선택하세요. 버린 카드의 슬롯은 양측의 결정을 마친 뒤 보충합니다.</p>${button(b.step==='attacker'?'공격자 선택 완료 →':'전투 카드 처리 완료 →',{type:'combat_pass'},'primary full')}`;}
 if(s.phase==='draw')return content+`<span class="pending-tag">${Object.values(s.rounds).every(n=>n===6)?'6개 행동 라운드 완료':'양 진영 남은 카드 없음'}</span><h3 class="subheading">다음 턴을 준비하세요.</h3><p class="instruction">남은 카드 수만큼 앞면 전투 카드를 버릴 수 있습니다. 전쟁 상황 페이즈 등 나머지 기본 게임 절차를 처리한 뒤 전략 카드를 받으세요.</p><p class="helper-note">버리기: 동맹군 ${s.draw_discards.cp}/${s.draw_allowance.cp} · 연합군 ${s.draw_discards.ap}/${s.draw_allowance.ap}</p><label class="check"><input type="checkbox" id="phases-confirm"><span>기본 게임의 나머지 페이즈를 해결했습니다.</span></label><button class="primary full" id="next-turn" disabled>전략 카드 받고 다음 턴 →</button>`;
 if(s.phase==='resolve')return content+`<span class="pending-tag">${p.played.automatic_ops?'자동 작전값 1':`${esc(catalog[p.played.card].name)} · ${modes[p.played.mode]}`}</span><h3 class="subheading">게임판에서 효과를 해결하세요.</h3><p class="instruction">작전·이벤트의 실제 효과와 카드 문구의 추가 처리를 적용하세요. 다시 섞기가 필요하다면 슬롯 보충 전에 처리합니다.</p><label>전투가 발생했나요?<select id="attacker"><option value="${s.active}">${sides[s.active]} 공격</option><option value="${s.active==='cp'?'ap':'cp'}">${sides[s.active==='cp'?'ap':'cp']} 공격</option></select></label><button class="secondary full" id="start-battle">전투 카드 선택 열기</button><div class="button-row">${button('효과 해결 완료 →',{type:'resolve'},'primary full')}</div>`;
 if(!p){const noCards=s.sides[s.active].remaining===0;return content+`<div class="die-area"><span class="die">✥</span><div><div class="die-title">${sides[s.active]}의 선택</div><div class="die-subtitle">운명 주사위를 굴려 주세요.</div></div></div><p class="instruction">주사위가 이번 행동에 사용할 수 있는 슬롯을 정합니다. 최종 선택은 당신의 몫입니다.</p>${button(noCards?'남은 카드 없음 · 차례 넘기기':'운명 주사위 굴리기 ↗',{type:noCards?'skip':'roll'},'primary full')}${noCards?'':`<details class="manual-roll"><summary>실물 주사위 결과 입력</summary><div>${[1,2,3,4,5,6].map(value=>button(dieFace(value)+`<span class="die-index">${value}</span>`,{type:'roll',value},'')).join('')}</div></details>`}`;}
 if(p.forced)return content+`<div class="die-area"><span class="die">✦</span><div><div class="die-title">8월의 포성</div><div class="die-subtitle">기본+ 준비 · 첫 행동</div></div></div><p class="instruction">이번 행동에는 주사위를 굴리지 않습니다. C의 ‘8월의 포성’을 이벤트로 사용하세요.</p><span class="pending-tag">C 카드를 선택하세요</span>`;
 const die=game.dice[p.die-1];return content+`<div class="die-area">${dieFace(p.die)}<div><div class="die-title">${esc(die.title)}</div><div class="die-subtitle">운명 주사위 결과 ${p.die}</div></div></div><p class="instruction">${esc(die.detail)}</p>${p.status==='reveal'?'<span class="pending-tag">공개할 뒷면 카드를 선택하세요</span>':s.candidates.length?`<span class="pending-tag">${s.candidates.length}개 슬롯에서 선택 가능</span>`:s.available_actions.some(a=>a.type==='auto_ops')?button('카드 없이 작전값 1 받기',{type:'auto_ops'},'primary full'):'<p class="helper-note">선택 가능한 카드를 확인하세요.</p>'}<p class="helper-note">출처 · 게임별 플레이시트, 운명 주사위 ${p.die}</p>`;
}
function inspector(){
 const blank='<div class="panel-label">카드 살펴보기<small>YOUR DECISION</small></div><div class="selection-empty"><div class="outline-card">✦</div><p>앞면 카드를 클릭해 살펴보세요.<br>금색 테두리는 선택 가능한 카드입니다.</p></div>';
 if(!selected)return blank;
 const s=session.state,{side,slot}=selected,d=s.sides[side].display[slot],c=d?.card;if(!c)return blank+'<p class="helper-note">뒷면 카드는 운명 주사위가 지시할 때만 공개됩니다.</p>';
 const candidate=s.candidates.find(x=>side===s.active&&x.slot===slot);
 const combat=s.available_actions.filter(a=>a.type==='combat_play'&&side===s.battle?.side&&a.slot===slot);
 const discard=s.available_actions.find(a=>a.type==='draw_discard'&&a.side===side&&a.slot===slot);
 let html=`<div class="panel-label">${sides[side]} · 슬롯 ${slot}<small>#${String(c.number).padStart(2,'0')} / ${c.ops} OPS</small></div><img class="inspector-img" src="${esc(c.image)}" data-zoom="${c.id}" alt="${esc(c.name)} 확대"><h3 class="selected-title">${esc(c.name)}</h3>`;
 if(c.ruleCorrection)html+=`<p class="helper-note">${esc(c.ruleCorrection)}</p>`;
 if(discard)return html+button('받기 페이즈: 전투 카드 버리기',discard,'primary full');
 if(!candidate&&!combat.length)return html+'<p class="helper-note">현재 절차에서는 이 카드를 사용할 수 없습니다.</p>';
 const allowed=candidate?.modes||['event'];
 return html+`<form id="play-form" data-combat="${Boolean(combat.length)}"><div class="mode-grid">${allowed.map((mode,i)=>`<label><input type="radio" name="mode" value="${mode}" ${i===0?'checked':''}><span>${modes[mode]}</span></label>`).join('')}</div><label>사용 후 카드 위치<select name="destination"><option value="discard" ${c.id==='cp-01'&&allowed[0]==='event'?'':'selected'}>버린 더미</option><option value="removed" ${c.id==='cp-01'&&allowed[0]==='event'?'selected':''}>게임에서 제거</option></select></label>${combat.length?'':'<label class="check"><input type="checkbox" name="grants_cards"><span>이 카드 효과로 추가 카드를 받음<small>공통 2.2에 따라 남은 카드 수를 줄이지 않습니다.</small></span></label>'}<label class="check"><input type="checkbox" name="base_legal" required><span>원래 게임의 카드 사용 조건을 확인했습니다.<small>이벤트 선행 조건, 전투·이동·충원 가능 여부는 게임판에서 확인합니다.</small></span></label><button class="primary full" type="submit">${combat.length?'전투 카드 사용':'이 카드 사용'} →</button></form>`;
}
function logRows(events){return events.map(e=>`<div class="activity-row"><span class="log-index">${String(e.revision).padStart(2,'0')}</span><span>${esc(e.message)}${e.action.type==='note'?`<br><span class="muted">${esc(e.action.text)}</span>`:''}</span><time>${new Date(e.at).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'})}</time></div>`).join('');}
function historyView(){return heading('EVERY CHOICE MATTERS','플레이 기록','저장된 선택을 시간 순서대로 확인하세요.',``)+`<div class="info-box">현재 저장 파일: <b>${esc(session.save_path)}</b><br>리비전 ${session.revision} · 모든 선택의 행동과 상태 스냅샷을 보관합니다.</div><section class="panel"><table class="archive"><thead><tr><th>기록</th><th>선택과 결과</th><th>저장 시간</th></tr></thead><tbody>${session.history.slice().reverse().map(e=>`<tr><td>r${e.revision}</td><td>${esc(e.message)}${e.action.type==='note'?`<p>${esc(e.action.text)}</p>`:''}<details class="summary-details"><summary>선택 JSON</summary><pre>${esc(JSON.stringify(e.action,null,2))}</pre></details></td><td>${new Date(e.at).toLocaleString('ko-KR')}</td></tr>`).join('')}</tbody></table></section>`;}
function rulesView(){return heading('THE RULES AT YOUR TABLE','룰북 & 가이드','제공된 공통 규칙과 패스 오브 글로리 플레이시트를 기준으로 합니다.')+`<div class="guide-grid"><section class="panel"><div class="panel-label">운명 주사위 결과표<small>PLAY SHEET · P.1</small></div>${game.dice.map(d=>`<div class="rule-row"><span class="rule-die">${dieFace(d.value)}<small>${d.value}</small></span><div><strong>${esc(d.title)}</strong><p>${esc(d.detail)}</p></div></div>`).join('')}</section><div><section class="panel"><div class="panel-label">진행 순서<small>COMMON RULES · P.1</small></div><ol class="rules-copy"><li>두 진영의 A/B를 앞면으로, D/E를 뒷면으로 준비합니다. C는 별도 카드가 아닌 받기 더미의 맨 위입니다.</li><li>남은 카드가 있으면 운명 주사위를 굴리고, 허용된 앞면 카드 중 한 장을 선택합니다.</li><li>기본 게임의 사용 조건을 확인하고 카드를 사용합니다. 추가 카드를 받는 효과가 없다면 남은 카드를 1 줄입니다.</li><li>게임판에서 카드 효과와 다시 섞기를 처리한 뒤 슬롯을 보충하고 상대 차례로 넘어갑니다.</li></ol></section><section class="panel"><h3>게임별 예외</h3><ul class="rules-copy"><li>핸드가 7장 또는 8장이더라도 양측은 턴마다 6개 행동 라운드만 진행합니다.</li><li>받기 페이즈에는 남은 카드 수만큼 앞면 전투 카드를 버릴 수 있습니다. 이후 남은 카드 수를 최대치로 맞추고 A/B/D/E의 빈 슬롯을 뒷면으로 채웁니다.</li><li>받기 더미 고갈 시 보충을 멈추고 남은 카드가 4보다 크면 4로 낮춥니다. 고갈 때문에 선택할 카드가 없을 때만 자동 작전값 1을 받습니다.</li><li>전투 이벤트는 전투 중에만 사용합니다. 공격자 → 방어자 순서로 결정하며, 버린 카드의 슬롯은 원래 면 상태로 보충합니다.</li><li>고갈 다시 섞기는 남은 뒷면 디스플레이 카드를 포함합니다. 전쟁 투입 단계 상승은 디스플레이 전체를 함께 섞고 A/B를 공개해 다시 준비합니다.</li></ul></section></div></div><div class="guide-grid"><section class="panel"><h3>자료 간 차이와 적용 기준</h3><div class="info-box"><b>사용자 확인: 마타 하리 = 동맹군 #17</b><br>PDF의 #22 표기를 카드 이미지 기준 #17로 정정했습니다. 연합군 #23 ‘첩보 활동’과 함께 상대 디스플레이를 모두 공개하고 작전 카드로 사용합니다.</div><p class="rules-copy">이미지에는 ‘8월의 총성’, ‘전면전’ 등 다른 번역이 남아 있습니다. 앱의 안내 문구는 PDF의 ‘8월의 포성’, ‘총력전’ 용어를 사용합니다.</p><p class="rules-copy">이 앱은 솔로 카드 선택과 기록을 관리합니다. 지도, 유닛, 승점, 이벤트의 선행 조건과 실제 효과는 기본 게임에서 해결하고 메모로 기록하세요. PDF에 상세 절차가 없는 전투 이벤트 유지·재사용은 자동화하지 않습니다. 앱에서는 버림·제거되는 전투 카드를 처리하고, 지속 효과는 게임판과 메모에서 관리합니다.</p></section><section class="panel"><h3>공식 보드 · 운명 주사위</h3><p class="rules-copy">제공된 GMT Print &amp; Play Kit의 파랑·초록 디스플레이와 주사위 도안을 적용했습니다. 보드 색상은 진영 구분용입니다. 1번 면의 !!는 이 게임에서 효과가 없습니다.</p><a class="source-link" target="_blank" rel="noopener" href="./assets/official/board-blue.jpg">↗ 파랑 카드 디스플레이</a><a class="source-link" target="_blank" rel="noopener" href="./assets/official/board-green.jpg">↗ 초록 카드 디스플레이</a><a class="source-link" target="_blank" rel="noopener" href="./assets/official/dice-and-counters.jpg">↗ 공식 주사위 · 마커 도안 © 2022 GMT Games</a><h3 class="subheading">제공된 PDF 원문</h3><a class="source-link" target="_blank" rel="noopener" href="./rules/CDG솔로시스템-공통규칙_공식용어수정.pdf">↗ CDG 솔로 시스템 · 공통 규칙 (1쪽)</a><a class="source-link" target="_blank" rel="noopener" href="./rules/CDG솔로시스템-패스오브글로리_공식용어수정.pdf">↗ 패스 오브 글로리 · 플레이시트 (1쪽)</a><p class="helper-note">게임별 플레이시트와 공통 규칙이 충돌하면 플레이시트가 우선합니다. 카드 이미지의 이벤트 조건도 직접 확인하세요.</p><h3 class="subheading">다른 게임을 추가하려면</h3><p class="rules-copy">개발 지침은 프로젝트의 <b>AGENTS.md</b>, <b>docs/ADDING_GAMES.md</b>에 있습니다. 공통 저장 기능과 게임별 규칙 어댑터를 분리해 두었습니다.</p></section></div>`;}
function llmView(){return heading('A SECOND PERSPECTIVE','LLM 함께하기','공개된 테이블을 공유하고, 제안된 선택을 검토해 적용하세요.')+`<div class="guide-grid"><section class="panel"><span class="eyebrow">01 / SHARE THE TABLE</span><h2>현재 상황을 전달하세요.</h2><ol class="llm-instructions"><li>게임판 상황을 테이블 메모로 기록하세요.</li><li>공개 상태 JSON을 내려받거나 복사해 원하는 LLM에 전달하세요.</li><li>가능한 행동 중 하나를 JSON으로 제안하도록 요청하세요.</li></ol><div class="button-row"><button class="primary" id="download-llm">↓ 공개 상태 JSON</button><button class="secondary" id="copy-llm">JSON 복사</button></div><div class="info-box">공유용 JSON에는 뒷면 카드의 정체와 받기 더미 순서가 없습니다. 전체 저장 파일에는 복구를 위한 비공개 상태도 들어 있습니다.</div><details><summary class="summary-details">현재 공개 상태 미리보기</summary><pre id="llm-preview">불러오는 중…</pre></details><p class="helper-note">외부 LLM API를 자동 호출하지 않습니다. 원하는 LLM과 파일을 주고받는 방식입니다.</p></section><section class="panel"><span class="eyebrow">02 / REVIEW THE CHOICE</span><h2>LLM의 선택을 검토하세요.</h2><p class="muted">아래 형식의 JSON을 붙여 넣으세요. 선택은 확인 버튼을 누른 뒤에만 반영됩니다.</p><pre id="llm-example">불러오는 중…</pre><label for="proposal-input">LLM 응답 JSON</label><textarea id="proposal-input" class="llm-textarea" spellcheck="false" placeholder='{"expected_revision": ${session.revision}, "action": {"type": "roll"}}'></textarea><button class="primary full" id="review-proposal">제안된 선택 확인 →</button><p class="helper-note">이미 진행된 리비전의 응답이나 규칙상 불가능한 행동은 규칙 엔진에서 거부합니다. 기본 게임의 합법성은 사람이 확인해야 합니다.</p></section></div>`;}
async function loadLLM(){try{const id=session.id,revision=session.revision;const data=await api(`/api/sessions/${id}/llm`);if(!session||session.id!==id||session.revision!==revision||currentView!=='llm')return;llmContext=data;if($('#llm-preview'))$('#llm-preview').textContent=JSON.stringify(data,null,2);if($('#llm-example'))$('#llm-example').textContent=JSON.stringify({expected_revision:data.revision,action:data.state.available_actions[0]||{type:'note',text:'현재 상황'}},null,2);}catch(e){toast(e.message,true);}}
async function download(kind){if(!session)return;try{const data=await api(`/api/sessions/${session.id}/${kind}`);const blob=new Blob([JSON.stringify(data,null,2)+'\n'],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`cdg-${kind==='llm'?'public':'save'}-${(data.id||data.session_id).slice(0,8)}-r${data.revision}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){toast(e.message,true);}}
async function openSessions(){try{const all=await api('/api/sessions');$('#sessions-dialog h2').textContent='저장된 게임';$('#session-list').innerHTML=all.length?all.map(s=>`<button class="session-button" data-load="${s.id}"><span>${esc(s.name)}<small>${s.turn}턴 · r${s.revision} · ${new Date(s.updated_at).toLocaleString('ko-KR')}</small></span><span>↗</span></button>`).join(''):'<p class="empty-small">아직 저장된 게임이 없습니다.</p>';$('#sessions-dialog').showModal();}catch(e){toast(e.message,true);}}
function inspectPile(side,pile){const ids=session.state.sides[side][pile];$('#sessions-dialog h2').textContent=`${sides[side]} · ${pile==='discard'?'버린 카드':'제거된 카드'}`;$('#session-list').innerHTML=ids.length?ids.map(id=>`<button class="session-button" data-zoom="${id}">${esc(catalog[id].name)} <small>#${catalog[id].number} · ${catalog[id].ops} OPS</small></button>`).join(''):'<p class="empty-small">카드가 없습니다.</p>';$('#sessions-dialog').showModal();}
function zoom(cid){const c=catalog[cid];if(!c)return;$('#zoom-image').src=c.image;$('#zoom-image').alt=c.name;$('#image-dialog').showModal();}
document.addEventListener('click',async e=>{
 const target=e.target.closest('button,a[data-view],img[data-zoom]');if(!target)return;
 if(target.classList.contains('close-dialog'))return target.closest('dialog').close();
 if(target.dataset.view){currentView=target.dataset.view;render();window.scrollTo({top:0,behavior:'instant'});return;}
 if(target.classList.contains('new-game'))return $('#setup-dialog').showModal();
 if(target.dataset.zoom)return zoom(target.dataset.zoom);
 if(['sessions-button','open-saves'].includes(target.id))return openSessions();
 if(target.dataset.pile)return inspectPile(...target.dataset.pile.split(':'));
 if(target.dataset.load){try{session=await api(`/api/sessions/${target.dataset.load}`);remember(session.id);selected=null;currentView='table';$('#sessions-dialog').close();render();saved();}catch(err){toast(err.message,true);}return;}
 if(busy)return;
 if(target.dataset.action)return act(JSON.parse(target.dataset.action));
 if(target.dataset.inspect){const [side,slot]=target.dataset.inspect.split(':');selected={side,slot};render();return;}
 if(target.dataset.war){const side=target.dataset.war,stage=target.dataset.stage;review({expected_revision:session.revision,action:{type:'reshuffle',side,reason:'war',stage,base_legal:true}});return;}
 if(target.id==='start-battle')return act({type:'battle_start',attacker:$('#attacker').value});
 if(target.id==='next-turn')return act({type:'next_turn',base_phases_done:$('#phases-confirm').checked});
 if(['download-save','export-save'].includes(target.id))return download('export');
 if(target.id==='import-save')return $('#import-file').click();
 if(target.id==='download-llm')return download('llm');
 if(target.id==='copy-llm'){try{llmContext=await api(`/api/sessions/${session.id}/llm`);await navigator.clipboard.writeText(JSON.stringify(llmContext,null,2));toast('공개 상태 JSON을 복사했습니다.');}catch{toast('복사할 수 없습니다. 공개 상태 JSON 다운로드를 이용하세요.',true);}return;}
 if(target.id==='review-proposal'){try{let raw=$('#proposal-input').value.trim();raw=raw.replace(/^```(?:json)?\s*/,'').replace(/\s*```$/,'');const data=JSON.parse(raw);if(!data||typeof data!=='object'||Array.isArray(data)||!Number.isInteger(data.expected_revision)||!data.action||typeof data.action!=='object'||Array.isArray(data.action)||typeof data.action.type!=='string')throw new Error('expected_revision과 action 객체를 포함한 JSON이 필요합니다.');if(data.expected_revision!==session.revision)throw new Error('현재 리비전과 다릅니다. 최신 공개 상태로 다시 요청하세요.');review(data);}catch(err){toast(err.message,true);}return;}
 if(target.id==='apply-proposal'&&$('#proposal-confirm').checked){$('#proposal-dialog').close();return act(proposal.action,proposal.expected_revision);}
});
function review(data){proposal=data;$('#proposal-preview').textContent=JSON.stringify(data,null,2);$('#proposal-confirm').checked=false;$('#apply-proposal').disabled=true;$('#proposal-dialog').showModal();}
document.addEventListener('change',e=>{if(e.target.id==='proposal-confirm')$('#apply-proposal').disabled=!e.target.checked;if(e.target.id==='phases-confirm')$('#next-turn').disabled=!e.target.checked;const form=e.target.closest('#play-form');if(form&&e.target.name==='mode'&&selected&&session.state.sides[selected.side].display[selected.slot]?.card?.id==='cp-01')form.elements.destination.value=e.target.value==='event'?'removed':'discard';});
document.addEventListener('submit',async e=>{e.preventDefault();const f=e.target;if(busy)return;
 if(f.id==='setup-form'){setBusy(true);status('첫 상태 저장 중…');try{const data=new FormData(f);session=await api('/api/sessions',{game:data.get('game'),name:data.get('name'),options:{max_hand:Number(data.get('max_hand')),guns:data.has('guns')}});remember(session.id);selected=null;currentView='table';$('#setup-dialog').close();render();saved();}catch(err){toast(err.message,true);status('저장 실패',true);}finally{setBusy(false);}return;}
 if(f.id==='play-form'){const data=new FormData(f);return act({type:f.dataset.combat==='true'?'combat_play':'play',slot:selected.slot,mode:data.get('mode'),destination:data.get('destination'),base_legal:data.has('base_legal'),grants_cards:data.has('grants_cards')});}
 if(f.id==='note-form'){const data=new FormData(f);return act({type:'note',text:data.get('note')});}
});
async function init(){try{store=await FileStore.open();const [games,cards]=await Promise.all([api('/api/games'),api('/api/catalog')]);game=games[0];catalog=cards;let remembered;try{remembered=localStorage.getItem('cdg-session:'+location.pathname);}catch{}if(remembered){try{session=await api(`/api/sessions/${remembered}`);}catch(e){if(e.status!==404&&e.status!==400)throw e;}}if(!session){const all=await api('/api/sessions');if(all.length)session=await api(`/api/sessions/${all[0].id}`);}render();saved();}catch(e){$('#main').innerHTML=`<div class="recovery"><h2>테이블을 불러오지 못했습니다.</h2><p>${esc(e.message)}</p><p>HTTPS 배포 주소 또는 localhost에서 최신 브라우저로 열어 주세요. 브라우저의 사이트 저장 공간도 확인하세요.</p><button class="secondary" id="retry">다시 불러오기</button></div>`;$('#retry').onclick=init;status('파일 저장소 확인 필요',true);}}
$('#import-file').addEventListener('change',async e=>{
 const file=e.target.files[0];e.target.value='';if(!file||busy||!store)return;
 setBusy(true);status('JSON 파일 확인 중…');
 try{if(file.size>100*1024*1024)throw new Error('100MB 이하의 저장 파일을 선택하세요.');session=await store.import(await file.text());remember(session.id);selected=null;llmContext=null;currentView='table';render();saved();toast('JSON 파일을 별도 게임으로 가져왔습니다.');}catch(error){toast(error.message,true);saved();}finally{setBusy(false);}
});
init();
