import {FileStore} from './physical-storage.js';
import {WAR_STAGES} from './games/physical-pog.js';

const $=selector=>document.querySelector(selector);
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const sides={cp:'동맹군',ap:'연합군'};
const views={table:'플레이 테이블',rules:'룰북 & 가이드',history:'플레이 기록'};
let store,session,game,view='table',busy=false,toastTimer;
const api=(path,body)=>store.request(path,body);
function toast(message,error=false){const el=$('#toast');el.textContent=message;el.classList.toggle('error',error);el.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.hidden=true,error?9000:4000);}
function status(message,error=false){const el=$('#save-status');el.classList.toggle('error',error);el.textContent=message;}
function saved(){status(session?`브라우저 JSON 저장됨 · r${session.revision}`:'브라우저 저장 준비');$('#export-save').disabled=!session;$('#undo-step').disabled=!session?.can_undo;}
function remember(sid){try{localStorage.setItem('cdg-session:'+location.pathname,sid);}catch{}}
function face(value){return `<span class="fate-face face-${value}" role="img" aria-label="운명 주사위 ${value}"></span>`;}
function heading(title,description){return `<div class="page-heading"><div><span class="eyebrow">PATHS OF GLORY · PHYSICAL TABLE</span><h1>${title}</h1><p class="muted">${description}</p></div></div>`;}
function welcome(){return heading('실물 카드 진행 헬퍼','카드는 테이블에서, 주사위와 남은 카드 수는 여기에서 관리하세요.')+`<section class="physical-welcome panel"><div class="welcome-die">✦</div><h2>카드를 놓고 시작하세요.</h2><p>양 진영의 실물 디스플레이를 준비하면, 운명 주사위 결과와 사용 가능한 카드 범위를 안내합니다.</p><button class="primary new-game">새 게임 시작 →</button></section>`;}
function meter(side,s){const remaining=s.sides[side].remaining;return `<section class="physical-meter ${side} ${s.phase==='action'&&s.active===side?'active':''}" aria-label="${sides[side]} 남은 카드"><span class="meter-name">${sides[side]}</span><strong>${remaining}<small> / ${s.max_hand}</small></strong><span class="meter-round">${s.rounds[side]} / 6 행동 완료</span></section>`;}
function actionView(s){
 if(s.phase==='draw')return `<section class="physical-action panel"><span class="eyebrow">TURN COMPLETE</span><h2>다음 턴 준비</h2><p>남은 카드 수만큼 앞면 전투 카드를 버릴 수 있습니다. 기본 게임의 나머지 페이즈를 해결한 뒤 전략 카드를 받으세요.</p><p class="instruction">받기 더미 고갈·다시 섞기와 전쟁 상황 페이즈는 실물 카드로 처리합니다. 다음 턴에는 남은 카드 수가 ${s.max_hand}로 초기화됩니다.</p><button class="primary full" data-action="next_turn">전략 카드 받고 다음 턴 →</button></section>`;
 if(s.pending){const g=s.guidance;return `<section class="physical-action panel"><div class="die-result">${s.pending.die?face(s.pending.die):'<span class="forced-icon">✦</span>'}<div><span class="eyebrow">${sides[s.active]} · ${s.pending.die?`주사위 ${s.pending.die}`:'첫 행동'}</span><h2>${esc(g.title)}</h2></div></div><div class="instruction-block"><b>먼저</b><p>${esc(g.before)}</p></div><div class="instruction-block main-instruction"><b>사용 가능한 카드</b><p>${esc(g.selection)}</p></div><div class="instruction-block"><b>사용한 뒤</b><p>실물 카드의 효과·다시 섞기를 먼저 해결하세요. ${esc(g.after)}</p></div><div class="helper-buttons"><button class="primary full" data-action="complete">카드 사용·보충 완료 →</button><button class="secondary full" data-action="complete-keep">추가 카드를 받아 카운트 유지하고 완료</button>${s.pending.forced?'':`<button class="text-button auto-ops" data-action="auto_ops">받기 더미 고갈로 선택할 카드 없음 · 자동 작전값 1</button>`}</div></section>`;}
 const zero=s.sides[s.active].remaining===0;return `<section class="physical-action panel"><span class="eyebrow">${sides[s.active]} · ${Math.min(6,s.rounds[s.active]+1)} / 6 행동</span><h2>${zero?'사용할 카드가 없습니다.':'운명 주사위를 굴리세요.'}</h2><p>${zero?'이번 진영의 행동을 넘기고 진행합니다.':'실물 카드 디스플레이를 확인하세요. 결과에 따른 공개·선택 범위를 안내합니다.'}</p><button class="primary full roll-button" data-action="${zero?'skip':'roll'}">${zero?'차례 넘기기 →':'운명 주사위 굴리기 ↗'}</button></section>`;
}
function warView(s){return `<section class="panel physical-rules-note"><h3>전쟁 투입 단계 · 카드 추가</h3><p>기본 게임에서 단계 상승 조건을 확인하세요. 해당 진영의 받기 더미·버린 더미·디스플레이 전체와 새 단계 카드를 함께 섞고, A/B는 앞면·D/E는 뒷면으로 놓으세요. C는 받기 더미 맨 위입니다.</p>${['cp','ap'].map(side=>`<div class="instruction-block"><b>${sides[side]} · ${WAR_STAGES[s.sides[side].war_stage]??'단계 미기록'}</b><div class="helper-buttons">${s.available_actions.filter(a=>a.type==='war_shuffle'&&a.side===side).map(a=>`<button class="secondary" data-action="war_shuffle" data-side="${side}" data-stage="${a.stage}">${WAR_STAGES[a.stage]} 카드 추가·재구성 완료</button>`).join('')}${s.sides[side].war_stage==='total'?'<p>총력전 카드까지 추가됨</p>':''}</div></div>`).join('')}<p class="muted">남은 카드 수는 다음 턴 시작 시 초기화됩니다. 이전 저장 파일의 단계는 미기록으로 표시합니다.</p></section>`;}
function recentRows(){return session.history.slice(-4).reverse().map(e=>`<div class="activity-row"><span class="log-index">${String(e.revision).padStart(2,'0')}</span><span>${esc(e.message)}${e.action.type==='note'?`<br><span class="muted">${esc(e.action.text)}</span>`:''}</span><time>${new Date(e.at).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'})}</time></div>`).join('');}
function tableView(){const s=session.state;return heading('패스 오브 글로리',esc(session.name))+`<section class="physical-status"><div><span>게임 턴</span><strong>${String(s.turn).padStart(2,'0')}</strong></div><div><span>진행</span><strong>${s.phase==='draw'?'다음 턴 준비':`${Math.min(6,s.rounds[s.active]+1)} / 6 행동`}</strong></div><div><span>차례</span><strong>${s.phase==='draw'?'양 진영':sides[s.active]}</strong></div></section><div class="physical-meters">${meter('cp',s)}${meter('ap',s)}</div>${actionView(s)}${s.phase==='action'&&s.sides[s.active].remaining>4?`<details class="physical-exhaustion"><summary>받기 더미가 고갈됐나요?</summary><p>실물 받기 더미가 비었다면 빈 슬롯 보충을 멈추고 남은 카드 수를 4로 낮춥니다.</p><button class="secondary" data-action="clamp_remaining">${sides[s.active]} 남은 카드 수를 4로 조정</button></details>`:''}<section class="activity-panel"><div class="section-heading"><h3>최근 기록</h3><button class="text-button" data-view="history">전체 기록 보기 ↗</button></div>${recentRows()}<form class="note-form" id="note-form"><input name="note" aria-label="게임판 상황 메모" maxlength="4000" required placeholder="게임판 상황과 선택 이유를 기록하세요…"><button class="secondary" type="submit">메모 저장 ＋</button></form></section>`;}
function rulesView(){return heading('룰북 & 가이드','실물 카드에 적용할 운명 주사위 결과표입니다.')+`<section class="panel physical-rules">${game.dice.map(d=>`<div class="physical-rule"><div>${face(d.value)}<small>${d.value}</small></div><div><h3>${esc(d.title)}</h3><p><b>공개</b> ${esc(d.before)}</p><p><b>선택</b> ${esc(d.selection)}</p><p><b>보충</b> ${esc(d.after)}</p></div></div>`).join('')}</section><section class="panel physical-rules-note"><h3>실물 카드 진행 메모</h3><p>C는 별도 카드가 아닌 받기 더미 맨 위입니다. 전투 카드는 공격자부터, 이어서 방어자가 사용 여부를 결정합니다. 버린 슬롯은 전투 종료 후 원래 면 상태로 채웁니다.</p><p>받기 더미가 고갈되면 빈 슬롯 보충을 멈추고 남은 카드 수가 4보다 크면 4로 낮춥니다. 주사위 결과상 사용할 카드가 없을 때만 자동 작전값 1을 사용합니다.</p><p>마타 하리는 사용자 확인에 따라 동맹군 #17입니다.</p><a class="source-link" target="_blank" rel="noopener" href="./rules/CDG솔로시스템-공통규칙_공식용어수정.pdf">↗ 공통 규칙 PDF</a><a class="source-link" target="_blank" rel="noopener" href="./rules/CDG솔로시스템-패스오브글로리_공식용어수정.pdf">↗ 패스 오브 글로리 플레이시트 PDF</a></section>`;}
function historyView(){return heading('플레이 기록','확정한 주사위와 진행 내용이 JSON 파일에 저장됩니다.')+`<section class="panel"><div class="info-box">${esc(session.save_path)} · 리비전 ${session.revision}</div><table class="archive"><thead><tr><th>기록</th><th>내용</th><th>시간</th></tr></thead><tbody>${session.history.slice().reverse().map(e=>`<tr><td>r${e.revision}</td><td>${esc(e.message)}${e.action.type==='note'?`<p>${esc(e.action.text)}</p>`:''}</td><td>${new Date(e.at).toLocaleString('ko-KR')}</td></tr>`).join('')}</tbody></table></section>`;}
function render(){
 $('#page-title').textContent=views[view];document.querySelectorAll('[data-view]').forEach(button=>button.classList.toggle('active',button.dataset.view===view));
 $('#main').innerHTML=view==='rules'?rulesView():!session?welcome():view==='history'?historyView():tableView();
 if(view==='table'&&session?.state.phase==='draw')$('.physical-action').insertAdjacentHTML('beforebegin',warView(session.state));
}
async function act(action,revision=session?.revision){if(busy||!session)return;busy=true;status('JSON 파일에 저장 중…');try{session=await api(`/api/sessions/${session.id}/actions`,{expected_revision:revision,action});busy=false;render();saved();toast(session.history.at(-1).message);}catch(error){status('저장되지 않음',true);toast(error.message,true);if(error.status===409){try{session=await api(`/api/sessions/${session.id}`);busy=false;render();saved();}catch{}}}finally{busy=false;}}
async function download(){if(!session)return;try{const data=await api(`/api/sessions/${session.id}/export`),url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)+'\n'],{type:'application/json'})),link=document.createElement('a');link.href=url;link.download=`pog-physical-${data.id.slice(0,8)}-r${data.revision}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(error){toast(error.message,true);}}
async function openSessions(){try{const all=await api('/api/sessions');$('#session-list').innerHTML=all.length?all.map(s=>`<button class="session-button" data-load="${s.id}"><span>${esc(s.name)}<small>${s.turn}턴 · r${s.revision}${s.legacy?' · 이전 카드 UI 저장 파일':''}</small></span><span>↗</span></button>`).join(''):'<p>저장된 게임이 없습니다.</p>';$('#sessions-dialog').showModal();}catch(error){toast(error.message,true);}}
document.addEventListener('click',async event=>{
 const target=event.target.closest('button');if(!target)return;
 if(target.classList.contains('new-game'))return $('#setup-dialog').showModal();
 if(target.classList.contains('close-dialog'))return target.closest('dialog').close();
 if(target.dataset.view){view=target.dataset.view;render();return;}
 if(target.dataset.load){try{session=await api(`/api/sessions/${target.dataset.load}`);remember(session.id);view='table';$('#sessions-dialog').close();render();saved();if(session.history[0]?.action?.type==='migrate_legacy')toast('이전 저장 파일에서 옮겼습니다. 실물 카드 배치를 확인하세요.');}catch(error){toast(error.message,true);}return;}
 if(target.id==='sessions-button'||target.id==='open-saves')return openSessions();
 if(target.id==='export-save')return download();
 if(target.id==='undo-step')return act({type:'undo'});
 if(target.id==='import-save')return $('#import-file').click();
 if(!target.dataset.action)return;
 const type=target.dataset.action;
 if(type==='war_shuffle')return act({type,side:target.dataset.side,stage:target.dataset.stage});
 if(type==='complete-keep')return act({type:'complete',keep_remaining:true});
 if(type==='auto_ops')return act({type:'auto_ops',deck_exhausted:true});
 return act({type});
});
document.addEventListener('submit',async event=>{event.preventDefault();const form=event.target;if(form.id==='setup-form'){if(busy)return;busy=true;try{const data=new FormData(form);session=await api('/api/sessions',{game:'paths-of-glory',name:data.get('name'),options:{max_hand:Number(data.get('max_hand')),guns:data.has('guns')}});remember(session.id);$('#setup-dialog').close();view='table';render();saved();toast('새 게임을 준비했습니다.');}catch(error){toast(error.message,true);}finally{busy=false;}}else if(form.id==='note-form'){const text=form.elements.note.value;await act({type:'note',text});}});
$('#import-file').addEventListener('change',async event=>{const file=event.target.files[0];event.target.value='';if(!file)return;try{session=await store.import(await file.text());remember(session.id);view='table';render();saved();toast('별도 게임으로 가져왔습니다. 실물 카드 배치를 확인하세요.');}catch(error){toast(error.message,true);}});
async function init(){try{store=await FileStore.open();game=(await api('/api/games'))[0];let remembered;try{remembered=localStorage.getItem('cdg-session:'+location.pathname);}catch{}if(remembered){try{session=await api(`/api/sessions/${remembered}`);remember(session.id);}catch(error){if(error.status!==404&&error.status!==400)throw error;}}if(!session){const all=await api('/api/sessions');if(all.length){session=await api(`/api/sessions/${all[0].id}`);remember(session.id);}}render();saved();}catch(error){$('#main').innerHTML=`<div class="recovery"><h2>테이블을 불러오지 못했습니다.</h2><p>${esc(error.message)}</p><button class="secondary" id="retry">다시 불러오기</button></div>`;$('#retry').onclick=init;status('파일 저장소 확인 필요',true);}}
init();
